/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.woytuloo.accountingapp.component;

import com.formdev.flatlaf.ui.FlatComboBoxUI;
import com.woytuloo.accountingapp.handlers.FontHandler;
import com.woytuloo.accountingapp.main.AppFrame;

import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import javax.swing.*;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;
import javax.swing.plaf.basic.BasicComboBoxUI;

/**
 * @author wojte
 */
public class InvoiceComboDataTile extends javax.swing.JPanel {

    public boolean big;
    private String parameterName;
    private String value;
    int index;
    private DefaultComboBoxModel<String> comboBoxModel;
    Font montserrat18 = FontHandler.montserrat18;


    /**
     * Creates new form InvoiceDataTile
     */
    public InvoiceComboDataTile() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        invoiceTile2 = new com.woytuloo.accountingapp.component.RoundedTile();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nazwa Parametru");


        jComboBox1.setBackground(new java.awt.Color(30, 30, 30));
        jComboBox1.setMaximumRowCount(8);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>());
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jComboBox1.setEditable(true);


        javax.swing.GroupLayout invoiceTile2Layout = new javax.swing.GroupLayout(invoiceTile2);
        invoiceTile2.setLayout(invoiceTile2Layout);
        invoiceTile2Layout.setHorizontalGroup(
                invoiceTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceTile2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, 0, 536, Short.MAX_VALUE)
                                .addContainerGap())
        );
        invoiceTile2Layout.setVerticalGroup(
                invoiceTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceTile2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(invoiceTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComboBox1)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(invoiceTile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(invoiceTile2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );



    }// </editor-fold>//GEN-END:initComponents


    private void initComponents2() {

        invoiceTile2 = new com.woytuloo.accountingapp.component.RoundedTile();
        jLabel1 = new javax.swing.JLabel();
        jTextArea = new javax.swing.JTextArea();

        setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nazwa Parametru");


        jTextArea.setBackground(new java.awt.Color(30, 30, 30));

        jTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextArea.setEditable(true);


        javax.swing.GroupLayout invoiceTile2Layout = new javax.swing.GroupLayout(invoiceTile2);
        invoiceTile2.setLayout(invoiceTile2Layout);
        invoiceTile2Layout.setHorizontalGroup(
                invoiceTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceTile2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextArea, 0, 536, Short.MAX_VALUE)
                                .addContainerGap())
        );
        invoiceTile2Layout.setVerticalGroup(
                invoiceTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, invoiceTile2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(invoiceTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextArea)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(invoiceTile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(invoiceTile2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );



    }// </editor-fold>//GEN-END:initComponents


    public InvoiceComboDataTile(String parameterName, int i) {
        this.index = i;
        this.parameterName = parameterName;
        System.out.println(parameterName);
        initComponents();
        jLabel1.setText(parameterName);

        jLabel1.setFont(montserrat18);
        jComboBox1.setPopupVisible(false);
        jComboBox1.setFont(montserrat18.deriveFont(16f));


        jComboBox1.setUI(new FlatComboBoxUI() {
            @Override
            protected JButton createArrowButton() {
                return new JButton() {
                    @Override
                    public int getWidth() {
                        return 100;
                    }
                };
            }
        });

        jComboBox1.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_DOWN || e.getKeyCode() == KeyEvent.VK_UP || e.getKeyCode() == KeyEvent.VK_ENTER) {
                    e.consume();
                }
            }
        });

        Component arrowButton = jComboBox1.getComponent(0);
        if (arrowButton instanceof JButton) {
            arrowButton.setEnabled(false);
            for (MouseListener ml : arrowButton.getMouseListeners()) {
                arrowButton.removeMouseListener(ml);
            }
        }
        jComboBox1.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                jComboBox1.setPopupVisible(false);
                e.consume();
            }
        });

        Component[] components = jComboBox1.getComponents();
        for (Component c : components) {
            if (c instanceof JButton) {
                c.setVisible(false);
                c.setBackground(jComboBox1.getBackground());
            }
        }



        jComboBox1.revalidate();
        jComboBox1.repaint();

    }


    public InvoiceComboDataTile(String parameterName, int i, boolean big) {
        this.index = i;
        this.big = big;
        this.parameterName = parameterName;
        System.out.println(parameterName);
        initComponents2();
        jLabel1.setText(parameterName);

        jLabel1.setFont(montserrat18);

        jTextArea.setFont(montserrat18.deriveFont(16f));

        jTextArea.setSize(jTextArea.getWidth(), jTextArea.getHeight());






    }
    public InvoiceComboDataTile(String parameterName, int i, boolean big, String data) {
        this.index = i;
        this.big = big;
        this.parameterName = parameterName;
        System.out.println(parameterName);
        initComponents2();
        jLabel1.setText(parameterName);

        jLabel1.setFont(montserrat18);

        jTextArea.setFont(montserrat18.deriveFont(16f));

        jTextArea.setSize(jTextArea.getWidth(), jTextArea.getHeight());
        jTextArea.setText(data);





    }

    public InvoiceComboDataTile(String parameterName, String value, int i) {
        this.index = i;
        this.parameterName = parameterName;
        System.out.println(parameterName);
        initComponents();
        jComboBox1.setSelectedItem(value);
        jComboBox1.setFont(montserrat18.deriveFont(16f));
        jLabel1.setText(parameterName);
        jLabel1.setFont(montserrat18);
    }

    public void setSuggestions(List<String> suggestions) {
        comboBoxModel.removeAllElements();
        for (String suggestion : suggestions) {
            comboBoxModel.addElement(suggestion);
        }
    }

    public String getComboBoxValue() {
        if(jComboBox1 == null)
            return jTextArea.getText().replaceAll("\n", " ");

        return (String) jComboBox1.getSelectedItem();
    }

    public String getParameterName() {
        return parameterName;
    }

    public JComboBox<String> getComboBox() {
        return jComboBox1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.woytuloo.accountingapp.component.RoundedTile invoiceTile2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
