/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.woytuloo.accountingapp.component;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author wojte
 */
public class mvPanel extends javax.swing.JPanel {

    /**
     * Creates new form mvPanel
     */
    public mvPanel() {
        initComponents();
        ImageIcon icon = new ImageIcon (getClass().getResource("/Images/mainIcon.png"));
        Image img = icon.getImage().getScaledInstance(160, 120,  java.awt.Image.SCALE_SMOOTH);
        logoLabel1.setIcon(new ImageIcon(img));
        
    }
    
    
    private int x,y;
    
    
    public void initMv(JFrame f){
        this.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent me){
                x = me.getX();
                y = me.getY();
                
            }
        
        });
        
        
        this.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent me) {
                int newX = me.getXOnScreen() - x - 6;        //  -14 - to cancel out the horizontal movement when frame is decorated
                int newY = me.getYOnScreen() - y - 34;       //  -31 - to cancel out the vertical movement when frame is decorated
                f.setLocation(newX, newY);

            }
        });
    }

    
    
    
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        Color c = new Color (30,40,60);
        g2.setColor(c);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
          
        
    }
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel1 = new com.woytuloo.accountingapp.component.LogoLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 45, 45));
        setPreferredSize(new java.awt.Dimension(185, 185));

        logoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wiewior3.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabel1.setText("InvoiceHollow");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.woytuloo.accountingapp.component.LogoLabel logoLabel1;
    // End of variables declaration//GEN-END:variables
}
