/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.woytuloo.accountingapp.main;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.woytuloo.accountingapp.InvoiceManagement.WorkingInvoice;
import com.woytuloo.accountingapp.InvoiceManagement.InvoiceBlueprintAdder;
import com.woytuloo.accountingapp.component.ButtonPanel;
import com.woytuloo.accountingapp.component.ControllJButton;
import com.woytuloo.accountingapp.component.RoundedInfoPanel;
import com.woytuloo.accountingapp.handlers.ConfigStorage;
import com.woytuloo.accountingapp.handlers.FontHandler;
import com.woytuloo.accountingapp.menu.Menu;
import com.woytuloo.accountingapp.layout.WrapLayout;

import java.awt.*;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.geom.Path2D;
import java.io.IOException;
import java.io.InputStream;
import java.util.Map;
import javax.swing.*;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author wojte
 */
public class AppFrame extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */

        private Shape createCustomShape(int width, int height) {
        int arcSize = 15;
        Path2D path = new Path2D.Double();

        path.moveTo(0, arcSize);
        path.quadTo(0, 0, arcSize, 0);
        path.lineTo(width, 0);
        path.lineTo(width, height);
        path.lineTo(0, height);
        path.closePath();

        return path;
    }

    public AppFrame() {
        FlatDarculaLaf.setup();
        SwingUtilities.updateComponentTreeUI(this);

        initComponents();

        this.setShape(createCustomShape(getWidth(), getHeight()));
        this.setBackground(new Color(0,0,0,0));
        mvPanel1.initMv(this);
        topMvPanelPlusButtons1.initMv(this);

        initCardLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        customScrollpane2 = new com.woytuloo.accountingapp.component.CustomScrollpane();
        menu1 = new com.woytuloo.accountingapp.menu.Menu();
        mvPanel1 = new com.woytuloo.accountingapp.component.mvPanel();
        topMvPanelPlusButtons1 = new com.woytuloo.accountingapp.component.TopMvPanelPlusButtons();
        controllJButton1 = new com.woytuloo.accountingapp.component.ControllJButton();
        jLabel1 = new javax.swing.JLabel();
        controllJButtonMinimize1 = new com.woytuloo.accountingapp.component.ControllJButtonMinimize(this);
        jPanel2 = new javax.swing.JPanel();
        background1 = new com.woytuloo.accountingapp.component.Background();
        lastInvoicesCard = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lastInvoicesRenderPanel = new javax.swing.JPanel();
        //invoiceButtonPanel3 = new com.woytuloo.accountingapp.component.InvoiceButtonPanel();
        roundedTile3 = new com.woytuloo.accountingapp.component.RoundedTile();
        lastInvoicesSearchButton = new javax.swing.JButton();
        lastInvoicesSearchBar = new javax.swing.JTextField();
        dashBoardPanelCard = new javax.swing.JPanel();
        dashboardChartDisplayPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel();
        dashboardInfoDataPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel2(new java.awt.Color(20, 20, 20));
        yearlyIncomeProgressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        incomeThisMonthPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel3();
        incomeThisMonthLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        thisMonthlyTargetPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel3();
        jLabel7 = new javax.swing.JLabel();
        thisMonthsTargetLabel = new javax.swing.JLabel();
        invoicesThisMonthPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel3();
        roundedInfoPanel34 = new com.woytuloo.accountingapp.component.RoundedInfoPanel3();
        jLabel8 = new javax.swing.JLabel();
        thisMonthInvoiceCountLabel = new javax.swing.JLabel();
        archiveMenuCard = new javax.swing.JPanel();
        lastInvoicesChoice = new javax.swing.JPanel();
        buttonPanel1 = new com.woytuloo.accountingapp.component.ButtonPanel();
        registryChoice = new javax.swing.JPanel();
        buttonPanel2 = new com.woytuloo.accountingapp.component.ButtonPanel();
        blueprintsChoice = new javax.swing.JPanel();
        buttonPanel3 = new com.woytuloo.accountingapp.component.ButtonPanel();
        remeberedPhrasesCard = new javax.swing.JPanel();
        roundedTile4 = new com.woytuloo.accountingapp.component.RoundedTile();
        suggestionsComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        suggestionsDisplayTextArea = new javax.swing.JTextArea();
        deleteSavedAutoFillCellButton = new javax.swing.JButton();
        editSavedAutoFillCellButton = new javax.swing.JButton();
        savedInvoiceBlueprintCards = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        savedInvoiceBlueprintDisplayPanel = new javax.swing.JPanel();
        fillInvoiceDataCard = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fillInvoiceDataRenderPanel = new javax.swing.JPanel();
        invoiceDataTile1 = new com.woytuloo.accountingapp.component.InvoiceDataTile();
        fillInvoiceGenerateButton = new javax.swing.JButton();
        choseInvoiceCard = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        choseInvoiceDisplayPanel = new javax.swing.JPanel();
        selectInvoiceFileCard = new javax.swing.JPanel();
        roundedTile1 = new com.woytuloo.accountingapp.component.RoundedTile();
        selectInvoiceNameTextField = new javax.swing.JTextField();
        selectInvoiceFileButton = new javax.swing.JButton();
        proceedToTemplateConfigurationButton = new javax.swing.JButton();
        fillFormCard = new javax.swing.JPanel();
        roundedTile2 = new com.woytuloo.accountingapp.component.RoundedTile();
        parameterNameTf = new javax.swing.JTextField();
        cellNameTf = new javax.swing.JTextField();
        addNewParameterButton = new javax.swing.JButton();
        paramCellCombo = new javax.swing.JComboBox<>();
        saveForm = new javax.swing.JButton();
        autoParamChoice = new javax.swing.JComboBox<>();
        deleteParameterButton = new javax.swing.JButton();
        textAlignmentCombo = new javax.swing.JComboBox<>();
        entrySubstringTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 20));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(60, 70, 150));

        menu1.setBackground(new java.awt.Color(20, 20, 20));
        customScrollpane2.setViewportView(menu1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(customScrollpane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mvPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(customScrollpane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        topMvPanelPlusButtons1.setBackground(new java.awt.Color(15, 15, 15));

        controllJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                controllJButton1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(230, 230, 230));
        jLabel1.setFont(FontHandler.montserrat14); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 230, 230));
        jLabel1.setText("InvoiceHollow");

        controllJButtonMinimize1.setBackground(new java.awt.Color(15, 15, 15));
        controllJButtonMinimize1.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout topMvPanelPlusButtons1Layout = new javax.swing.GroupLayout(topMvPanelPlusButtons1);
        topMvPanelPlusButtons1.setLayout(topMvPanelPlusButtons1Layout);
        topMvPanelPlusButtons1Layout.setHorizontalGroup(
            topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topMvPanelPlusButtons1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(controllJButtonMinimize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(controllJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topMvPanelPlusButtons1Layout.setVerticalGroup(
            topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topMvPanelPlusButtons1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(topMvPanelPlusButtons1Layout.createSequentialGroup()
                .addGroup(topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(controllJButtonMinimize1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controllJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setOpaque(false);

        background1.setOpaque(true);
        cardLayout = new CardLayout();
        background1.setLayout(new java.awt.CardLayout());
        background1.setLayout(cardLayout);

        lastInvoicesCard.setOpaque(false);

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setAutoscrolls(true);
        jScrollPane6.setOpaque(false);
        jScrollPane6.setViewportView(null);
        jScrollPane6.getViewport().setOpaque(false);
        jScrollPane6.getVerticalScrollBar().setUnitIncrement(20);

        lastInvoicesRenderPanel.setBackground(new java.awt.Color(204, 0, 51));
        lastInvoicesRenderPanel.setOpaque(false);

        lastInvoicesRenderPanel.setLayout(new WrapLayout(FlowLayout.LEFT, 30, 30));

        jScrollPane6.setViewportView(lastInvoicesRenderPanel);

        lastInvoicesSearchButton.setBackground(new java.awt.Color(30, 30, 30));
        lastInvoicesSearchButton.setIcon(new ImageIcon(new ImageIcon (getClass().getResource("/Images/searchIcon.png")).getImage().getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH)));
        lastInvoicesSearchButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lastInvoicesSearchBar.setBackground(new java.awt.Color(20, 20, 20));
        lastInvoicesSearchBar.setText("Wyszukaj fakturę  (numer, data, adres)");
        lastInvoicesSearchBar.setFont(FontHandler.montserrat14);
        lastInvoicesSearchBar.setBorder(new com.woytuloo.accountingapp.component.RoundedBorder(new java.awt.Color(60, 60, 60), 1, 6));
        lastInvoicesSearchBar.setCaretColor(new java.awt.Color(200, 200, 200));
        lastInvoicesSearchBar.setForeground(new java.awt.Color(200, 200, 200));

        javax.swing.GroupLayout roundedTile3Layout = new javax.swing.GroupLayout(roundedTile3);
        roundedTile3.setLayout(roundedTile3Layout);
        roundedTile3Layout.setHorizontalGroup(
            roundedTile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedTile3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastInvoicesSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastInvoicesSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roundedTile3Layout.setVerticalGroup(
            roundedTile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedTile3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedTile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastInvoicesSearchBar)
                    .addComponent(lastInvoicesSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout lastInvoicesCardLayout = new javax.swing.GroupLayout(lastInvoicesCard);
        lastInvoicesCard.setLayout(lastInvoicesCardLayout);
        lastInvoicesCardLayout.setHorizontalGroup(
            lastInvoicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastInvoicesCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lastInvoicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedTile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lastInvoicesCardLayout.setVerticalGroup(
            lastInvoicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastInvoicesCardLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(roundedTile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background1.add(lastInvoicesCard, "card5");

        dashBoardPanelCard.setForeground(new java.awt.Color(255, 255, 255));
        dashBoardPanelCard.setOpaque(false);

        dashboardChartDisplayPanel.setBackground(new java.awt.Color(255, 0, 102));

        dashboardInfoDataPanel.setBackground(new java.awt.Color(15, 15, 15));
        dashboardInfoDataPanel.setOpaque(true);

        yearlyIncomeProgressBar.setFont(FontHandler.montserrat18); // NOI18N
        yearlyIncomeProgressBar.setForeground(new java.awt.Color(51, 196, 32));
        yearlyIncomeProgressBar.setMaximum(200000);
        yearlyIncomeProgressBar.setStringPainted(true);

        jLabel2.setBackground(new java.awt.Color(230, 230, 230));
        jLabel2.setFont(FontHandler.montserrat18); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Podsumowanie");

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1094, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1094, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        incomeThisMonthPanel.setPreferredSize(new java.awt.Dimension(360, 244));

        incomeThisMonthLabel.setFont(FontHandler.montserrat48); // NOI18N
        incomeThisMonthLabel.setForeground(new java.awt.Color(230, 230, 230));
        incomeThisMonthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeThisMonthLabel.setText("0 zł");
        incomeThisMonthLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        incomeThisMonthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(FontHandler.montserrat24); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 230, 230));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dochód w tym miesiącu:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout incomeThisMonthPanelLayout = new javax.swing.GroupLayout(incomeThisMonthPanel);
        incomeThisMonthPanel.setLayout(incomeThisMonthPanelLayout);
        incomeThisMonthPanelLayout.setHorizontalGroup(
            incomeThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeThisMonthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incomeThisMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeThisMonthPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        incomeThisMonthPanelLayout.setVerticalGroup(
            incomeThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeThisMonthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(incomeThisMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        thisMonthlyTargetPanel.setPreferredSize(new java.awt.Dimension(360, 244));

        jLabel7.setFont(FontHandler.montserrat24); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Aktualny miesięczny cel:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        thisMonthsTargetLabel.setFont(FontHandler.montserrat48); // NOI18N
        thisMonthsTargetLabel.setForeground(new java.awt.Color(230, 230, 230));
        thisMonthsTargetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thisMonthsTargetLabel.setText("0 zł");
        thisMonthsTargetLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        thisMonthsTargetLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout thisMonthlyTargetPanelLayout = new javax.swing.GroupLayout(thisMonthlyTargetPanel);
        thisMonthlyTargetPanel.setLayout(thisMonthlyTargetPanelLayout);
        thisMonthlyTargetPanelLayout.setHorizontalGroup(
            thisMonthlyTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thisMonthlyTargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thisMonthlyTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thisMonthlyTargetPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(thisMonthsTargetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        thisMonthlyTargetPanelLayout.setVerticalGroup(
            thisMonthlyTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thisMonthlyTargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thisMonthsTargetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedInfoPanel34.setPreferredSize(new java.awt.Dimension(360, 244));

        jLabel8.setFont(FontHandler.montserrat24);
        jLabel8.setForeground(new java.awt.Color(230, 230, 230));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Faktury w tym miesiącu:");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        thisMonthInvoiceCountLabel.setFont(FontHandler.montserrat48);
        thisMonthInvoiceCountLabel.setForeground(new java.awt.Color(230, 230, 230));
        thisMonthInvoiceCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thisMonthInvoiceCountLabel.setText("0");
        thisMonthInvoiceCountLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        thisMonthInvoiceCountLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout roundedInfoPanel34Layout = new javax.swing.GroupLayout(invoicesThisMonthPanel);
        invoicesThisMonthPanel.setLayout(roundedInfoPanel34Layout);
        roundedInfoPanel34Layout.setHorizontalGroup(
            roundedInfoPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedInfoPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedInfoPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedInfoPanel34Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(thisMonthInvoiceCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundedInfoPanel34Layout.setVerticalGroup(
            roundedInfoPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedInfoPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thisMonthInvoiceCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
//
//        javax.swing.GroupLayout invoicesThisMonthPanelLayout = new javax.swing.GroupLayout(invoicesThisMonthPanel);
//        invoicesThisMonthPanel.setLayout(invoicesThisMonthPanelLayout);
//        invoicesThisMonthPanelLayout.setHorizontalGroup(
//            invoicesThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(invoicesThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(invoicesThisMonthPanelLayout.createSequentialGroup()
//                    .addContainerGap()
//                    .addComponent(roundedInfoPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//        );
//        invoicesThisMonthPanelLayout.setVerticalGroup(
//            invoicesThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 0, Short.MAX_VALUE)
//            .addGroup(invoicesThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                .addGroup(invoicesThisMonthPanelLayout.createSequentialGroup()
//                    .addContainerGap()
//                    .addComponent(roundedInfoPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addContainerGap()))
//        );

        javax.swing.GroupLayout dashboardInfoDataPanelLayout = new javax.swing.GroupLayout(dashboardInfoDataPanel);
        dashboardInfoDataPanel.setLayout(dashboardInfoDataPanelLayout);
        dashboardInfoDataPanelLayout.setHorizontalGroup(
            dashboardInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardInfoDataPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(dashboardInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearlyIncomeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1094, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashboardInfoDataPanelLayout.createSequentialGroup()
                        .addComponent(invoicesThisMonthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incomeThisMonthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thisMonthlyTargetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardInfoDataPanelLayout.setVerticalGroup(
            dashboardInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardInfoDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dashboardInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(thisMonthlyTargetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(incomeThisMonthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(invoicesThisMonthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(yearlyIncomeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout dashBoardPanelCardLayout = new javax.swing.GroupLayout(dashBoardPanelCard);
        dashBoardPanelCard.setLayout(dashBoardPanelCardLayout);
        dashBoardPanelCardLayout.setHorizontalGroup(
            dashBoardPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardPanelCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashBoardPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashboardInfoDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardChartDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashBoardPanelCardLayout.setVerticalGroup(
            dashBoardPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardPanelCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dashboardChartDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardInfoDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background1.add(dashBoardPanelCard, "card2");

        archiveMenuCard.setOpaque(false);

        lastInvoicesChoice.setBackground(new java.awt.Color(0, 153, 204));
        lastInvoicesChoice.setOpaque(false);

        buttonPanel1.setBorder(null);
        ImageIcon iconInvoice = new ImageIcon (getClass().getResource("/Images/lastinvoicesIcon.png"));
        Image imgInvoice = iconInvoice.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel1.setIcon(new ImageIcon(imgInvoice));
        buttonPanel1.setText("Ostatnie Faktury");
        buttonPanel1.setFont(FontHandler.montserrat18); // NOI18N
        buttonPanel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);


        javax.swing.GroupLayout lastInvoicesChoiceLayout = new javax.swing.GroupLayout(lastInvoicesChoice);
        lastInvoicesChoice.setLayout(lastInvoicesChoiceLayout);
        lastInvoicesChoiceLayout.setHorizontalGroup(
            lastInvoicesChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        lastInvoicesChoiceLayout.setVerticalGroup(
            lastInvoicesChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        registryChoice.setBackground(new java.awt.Color(153, 153, 255));
        registryChoice.setOpaque(false);

        ImageIcon iconReg = new ImageIcon (getClass().getResource("/Images/registryIcon.png"));
        Image imgReg = iconReg.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel2.setIcon(new javax.swing.ImageIcon(imgReg));
        buttonPanel2.setText("Spis podpowiedzi");
        buttonPanel2.setFont(FontHandler.montserrat18); // NOI18N
        buttonPanel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registryChoiceLayout = new javax.swing.GroupLayout(registryChoice);
        registryChoice.setLayout(registryChoiceLayout);
        registryChoiceLayout.setHorizontalGroup(
            registryChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        registryChoiceLayout.setVerticalGroup(
            registryChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        blueprintsChoice.setBackground(new java.awt.Color(255, 153, 204));
        blueprintsChoice.setOpaque(false);

        ImageIcon iconBp = new ImageIcon (getClass().getResource("/Images/blueprintsIcon.png"));
        Image imgBp = iconBp.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel3.setIcon(new javax.swing.ImageIcon(imgBp));
        buttonPanel3.setText("Szablony");
        buttonPanel3.setFont(FontHandler.montserrat18); // NOI18N
        buttonPanel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blueprintsChoiceLayout = new javax.swing.GroupLayout(blueprintsChoice);
        blueprintsChoice.setLayout(blueprintsChoiceLayout);
        blueprintsChoiceLayout.setHorizontalGroup(
            blueprintsChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blueprintsChoiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        blueprintsChoiceLayout.setVerticalGroup(
            blueprintsChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout archiveMenuCardLayout = new javax.swing.GroupLayout(archiveMenuCard);
        archiveMenuCard.setLayout(archiveMenuCardLayout);
        archiveMenuCardLayout.setHorizontalGroup(
            archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveMenuCardLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lastInvoicesChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(registryChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(blueprintsChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        archiveMenuCardLayout.setVerticalGroup(
            archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveMenuCardLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastInvoicesChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registryChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueprintsChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        background1.add(archiveMenuCard, "card4");

        remeberedPhrasesCard.setOpaque(false);

        suggestionsComboBox.setBackground(new java.awt.Color(30, 30, 30));
        suggestionsComboBox.setMaximumRowCount(8);
        suggestionsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        suggestionsComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suggestionsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestionsComboBoxActionPerformed(evt);
            }
        });

        suggestionsDisplayTextArea.setBackground(new java.awt.Color(30, 30, 30));
        suggestionsDisplayTextArea.setColumns(20);
        suggestionsDisplayTextArea.setRows(5);
        suggestionsDisplayTextArea.setBorder(new EmptyBorder(10, 10, 10, 10));
        suggestionsDisplayTextArea.setFont(FontHandler.montserrat14);

        jScrollPane1.setViewportView(suggestionsDisplayTextArea);
        jScrollPane1.setBackground(new java.awt.Color(30, 30, 30));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        deleteSavedAutoFillCellButton.setBackground(new java.awt.Color(30, 30, 30));
        deleteSavedAutoFillCellButton.setText("Usuń");
        deleteSavedAutoFillCellButton.setFont(FontHandler.montserrat14);
        deleteSavedAutoFillCellButton.setBorderPainted(false);

        editSavedAutoFillCellButton.setBackground(new java.awt.Color(30, 30, 30));
        editSavedAutoFillCellButton.setText("Zapisz");
        editSavedAutoFillCellButton.setFont(FontHandler.montserrat14);
        editSavedAutoFillCellButton.setBorderPainted(false);

        javax.swing.GroupLayout roundedTile4Layout = new javax.swing.GroupLayout(roundedTile4);
        roundedTile4.setLayout(roundedTile4Layout);
        roundedTile4Layout.setHorizontalGroup(
            roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile4Layout.createSequentialGroup()
                .addGroup(roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedTile4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(suggestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedTile4Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(deleteSavedAutoFillCellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editSavedAutoFillCellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        roundedTile4Layout.setVerticalGroup(
            roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedTile4Layout.createSequentialGroup()
                        .addComponent(suggestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteSavedAutoFillCellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editSavedAutoFillCellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout remeberedPhrasesCardLayout = new javax.swing.GroupLayout(remeberedPhrasesCard);
        remeberedPhrasesCard.setLayout(remeberedPhrasesCardLayout);
        remeberedPhrasesCardLayout.setHorizontalGroup(
            remeberedPhrasesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remeberedPhrasesCardLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(roundedTile4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        remeberedPhrasesCardLayout.setVerticalGroup(
            remeberedPhrasesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remeberedPhrasesCardLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(roundedTile4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        background1.add(remeberedPhrasesCard, "card4");

        savedInvoiceBlueprintCards.setOpaque(false);

        jScrollPane5.setBorder(null);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setAutoscrolls(true);
        jScrollPane5.setOpaque(false);
        jScrollPane5.setViewportView(null);
        jScrollPane4.getViewport().setOpaque(false);
        jScrollPane4.getVerticalScrollBar().setUnitIncrement(20);

        jScrollPane5.getViewport().setOpaque(false);
        savedInvoiceBlueprintDisplayPanel.setOpaque(false);
        savedInvoiceBlueprintDisplayPanel.setLayout(new WrapLayout(FlowLayout.LEFT, 30, 30));

        jScrollPane5.setViewportView(savedInvoiceBlueprintDisplayPanel);

        javax.swing.GroupLayout savedInvoiceBlueprintCardsLayout = new javax.swing.GroupLayout(savedInvoiceBlueprintCards);
        savedInvoiceBlueprintCards.setLayout(savedInvoiceBlueprintCardsLayout);
        savedInvoiceBlueprintCardsLayout.setHorizontalGroup(
            savedInvoiceBlueprintCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savedInvoiceBlueprintCardsLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        savedInvoiceBlueprintCardsLayout.setVerticalGroup(
            savedInvoiceBlueprintCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savedInvoiceBlueprintCardsLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        background1.add(savedInvoiceBlueprintCards, "card5");

        fillInvoiceDataCard.setOpaque(false);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setOpaque(false);
        jScrollPane3.setViewportView(null);
        jScrollPane3.getViewport().setOpaque(false);
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(20);

        fillInvoiceDataRenderPanel.setOpaque(false);
        fillInvoiceDataRenderPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 89);
        fillInvoiceDataRenderPanel.add(invoiceDataTile1, gridBagConstraints);

        jScrollPane3.setViewportView(fillInvoiceDataRenderPanel);

        fillInvoiceGenerateButton.setBackground(new java.awt.Color(15, 15, 15));
        fillInvoiceGenerateButton.setText("Generuj");
        fillInvoiceGenerateButton.setFont(FontHandler.montserrat14);
        fillInvoiceGenerateButton.setBorderPainted(false);
        fillInvoiceGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillInvoiceGenerateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fillInvoiceDataCardLayout = new javax.swing.GroupLayout(fillInvoiceDataCard);
        fillInvoiceDataCard.setLayout(fillInvoiceDataCardLayout);
        fillInvoiceDataCardLayout.setHorizontalGroup(
            fillInvoiceDataCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillInvoiceDataCardLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fillInvoiceDataCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fillInvoiceGenerateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        fillInvoiceDataCardLayout.setVerticalGroup(
            fillInvoiceDataCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillInvoiceDataCardLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(fillInvoiceGenerateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        background1.add(fillInvoiceDataCard, "card5");

        choseInvoiceCard.setOpaque(false);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setOpaque(false);
        jScrollPane4.setViewportView(null);
        jScrollPane4.getViewport().setOpaque(false);
        jScrollPane4.getVerticalScrollBar().setUnitIncrement(20);

        choseInvoiceDisplayPanel.setOpaque(false);
        choseInvoiceDisplayPanel.setLayout(new WrapLayout(FlowLayout.LEFT, 30, 30));


        jScrollPane4.setViewportView(choseInvoiceDisplayPanel);

        javax.swing.GroupLayout choseInvoiceCardLayout = new javax.swing.GroupLayout(choseInvoiceCard);
        choseInvoiceCard.setLayout(choseInvoiceCardLayout);
        choseInvoiceCardLayout.setHorizontalGroup(
            choseInvoiceCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choseInvoiceCardLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        choseInvoiceCardLayout.setVerticalGroup(
            choseInvoiceCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choseInvoiceCardLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        background1.add(choseInvoiceCard, "card5");

        selectInvoiceFileCard.setOpaque(false);

        selectInvoiceNameTextField.setBackground(new java.awt.Color(20, 20, 20));
        selectInvoiceNameTextField.setFont(FontHandler.montserrat18.deriveFont(16f)); // NOI18N
        selectInvoiceNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        selectInvoiceNameTextField.setText("Nazwa Szablonu");
        selectInvoiceNameTextField.setBorder(new com.woytuloo.accountingapp.component.RoundedBorder(new java.awt.Color(60, 60, 60), 1, 6));
        selectInvoiceNameTextField.setCaretColor(new java.awt.Color(200, 200, 200));
        selectInvoiceNameTextField.setForeground(new java.awt.Color(200, 200, 200));
        selectInvoiceNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selectInvoiceNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                selectInvoiceNameTextFieldFocusLost(evt);
            }
        });
        selectInvoiceNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInvoiceNameTextFieldActionPerformed(evt);
            }
        });

        selectInvoiceFileButton.setBackground(new java.awt.Color(30, 30, 30));
        selectInvoiceFileButton.setFont(FontHandler.montserrat14); // NOI18N
        selectInvoiceFileButton.setText("Wybierz plik");
        selectInvoiceFileButton.setBorderPainted(false);
        selectInvoiceFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInvoiceFileButtonActionPerformed(evt);
            }
        });

        proceedToTemplateConfigurationButton.setBackground(new java.awt.Color(30, 30, 30));
        proceedToTemplateConfigurationButton.setFont(FontHandler.montserrat14); // NOI18N
        proceedToTemplateConfigurationButton.setText("Przejdź do konfiguracji");
        proceedToTemplateConfigurationButton.setBorderPainted(false);
        proceedToTemplateConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedToTemplateConfigurationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedTile1Layout = new javax.swing.GroupLayout(roundedTile1);
        roundedTile1.setLayout(roundedTile1Layout);
        roundedTile1Layout.setHorizontalGroup(
            roundedTile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedTile1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(selectInvoiceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(roundedTile1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(selectInvoiceFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roundedTile1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(proceedToTemplateConfigurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedTile1Layout.setVerticalGroup(
            roundedTile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(selectInvoiceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectInvoiceFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(proceedToTemplateConfigurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout selectInvoiceFileCardLayout = new javax.swing.GroupLayout(selectInvoiceFileCard);
        selectInvoiceFileCard.setLayout(selectInvoiceFileCardLayout);
        selectInvoiceFileCardLayout.setHorizontalGroup(
            selectInvoiceFileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectInvoiceFileCardLayout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(roundedTile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        selectInvoiceFileCardLayout.setVerticalGroup(
            selectInvoiceFileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectInvoiceFileCardLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(roundedTile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        background1.add(selectInvoiceFileCard, "card2");

        fillFormCard.setOpaque(false);

        parameterNameTf.setBackground(new java.awt.Color(20, 20, 20));
        parameterNameTf.setFont(FontHandler.montserrat14); // NOI18N
        parameterNameTf.setText("Nazwa parametru");
        parameterNameTf.setBorder(new CompoundBorder(new com.woytuloo.accountingapp.component.RoundedBorder(new java.awt.Color(60, 60, 60), 1, 6), new EmptyBorder(0,10,0,0)));
        parameterNameTf.setCaretColor(new java.awt.Color(200, 200, 200));
        parameterNameTf.setForeground(new java.awt.Color(200, 200, 200));
        parameterNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                parameterNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                parameterNameTfFocusLost(evt);
            }
        });
        parameterNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameterNameTfActionPerformed(evt);
            }
        });

        cellNameTf.setBackground(new java.awt.Color(20, 20, 20));
        cellNameTf.setFont(FontHandler.montserrat14);
        cellNameTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cellNameTf.setText("Komórka  (np. B3)");
        cellNameTf.setBorder(new com.woytuloo.accountingapp.component.RoundedBorder(new java.awt.Color(60, 60, 60), 1, 6));
        cellNameTf.setCaretColor(new java.awt.Color(200, 200, 200));
        cellNameTf.setForeground(new java.awt.Color(200, 200, 200));
        cellNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cellNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cellNameTfFocusLost(evt);
            }
        });
        cellNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellNameTfActionPerformed(evt);
            }
        });

        addNewParameterButton.setBackground(new java.awt.Color(30, 30, 30));
        addNewParameterButton.setFont(FontHandler.montserrat14); // NOI18N
        addNewParameterButton.setText("Dodaj");
        addNewParameterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addNewParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewParameterButtonActionPerformed(evt);
            }
        });

        paramCellCombo.setBackground(new java.awt.Color(30, 30, 30));
        paramCellCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paramCellCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramCellComboActionPerformed(evt);
            }
        });

        saveForm.setBackground(new java.awt.Color(30, 30, 30));
        saveForm.setFont(FontHandler.montserrat14); // NOI18N
        saveForm.setText("Zapisz Szablon");
        saveForm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFormActionPerformed(evt);
            }
        });

        autoParamChoice.setBackground(new java.awt.Color(30, 30, 30));
        autoParamChoice.setFont(FontHandler.montserrat14); // NOI18N
        autoParamChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Automatyzuj>", "Numer", "Data", "Dopełnianie","Blok Tekstu", "Cena - Całkowita", "Cena - Ile sztuk", "Cena - Jednostkowa", "Cena - Słownie" }));
        autoParamChoice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        autoParamChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoParamChoiceActionPerformed(evt);
            }
        });

        deleteParameterButton.setBackground(new java.awt.Color(30, 30, 30));
        deleteParameterButton.setText("Usuń");
        deleteParameterButton.setFont(FontHandler.montserrat14);
        deleteParameterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteParameterButtonActionPerformed(evt);
            }
        });

        textAlignmentCombo.setBackground(new java.awt.Color(30, 30, 30));
        textAlignmentCombo.setFont(FontHandler.montserrat14); // NOI18N
        textAlignmentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Pozycja w komórce>", "Lewo", "Środek", "Prawo" }));
        textAlignmentCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textAlignmentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlignmentComboActionPerformed(evt);
            }
        });

        entrySubstringTf.setBackground(new java.awt.Color(20, 20, 20));
        entrySubstringTf.setFont(FontHandler.montserrat14); // NOI18N
        entrySubstringTf.setText("Aby otoczyć wartość tekstem, zapisz ją jako @ (np. tekst @ tekst)");
        entrySubstringTf.setBorder(new CompoundBorder(new com.woytuloo.accountingapp.component.RoundedBorder(new java.awt.Color(60, 60, 60), 1, 6), new EmptyBorder(0,10,0,0)));
        entrySubstringTf.setCaretColor(new java.awt.Color(200, 200, 200));
        entrySubstringTf.setForeground(new java.awt.Color(200, 200, 200));
        entrySubstringTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entrySubstringTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entrySubstringTfFocusLost(evt);
            }
        });
        entrySubstringTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrySubstringTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedTile2Layout = new javax.swing.GroupLayout(roundedTile2);
        roundedTile2.setLayout(roundedTile2Layout);
        roundedTile2Layout.setHorizontalGroup(
            roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(roundedTile2Layout.createSequentialGroup()
                        .addComponent(paramCellCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(deleteParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedTile2Layout.createSequentialGroup()
                        .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addNewParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entrySubstringTf, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(roundedTile2Layout.createSequentialGroup()
                                    .addComponent(parameterNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cellNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(autoParamChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(textAlignmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        roundedTile2Layout.setVerticalGroup(
            roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parameterNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAlignmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoParamChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(entrySubstringTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addNewParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramCellCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteParameterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout fillFormCardLayout = new javax.swing.GroupLayout(fillFormCard);
        fillFormCard.setLayout(fillFormCardLayout);
        fillFormCardLayout.setHorizontalGroup(
            fillFormCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillFormCardLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(roundedTile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        fillFormCardLayout.setVerticalGroup(
            fillFormCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillFormCardLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(roundedTile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        background1.add(fillFormCard, "card2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1214, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(background1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(topMvPanelPlusButtons1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topMvPanelPlusButtons1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );



        parameterNameTf.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if(parameterNameTf.getText().equals("Nazwa parametru")) {
                    parameterNameTf.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if(parameterNameTf.getText().isEmpty()) {
                    parameterNameTf.setText("Nazwa parametru");
                }
            }
        });

        entrySubstringTf.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if(entrySubstringTf.getText().equals("Aby otoczyć wartość tekstem, zapisz ją jako @ (np. tekst @ tekst)")) {
                    entrySubstringTf.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if(entrySubstringTf.getText().isEmpty()) {
                    entrySubstringTf.setText("Aby otoczyć wartość tekstem, zapisz ją jako @ (np. tekst @ tekst)");
                }
            }
        });

        cellNameTf.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if(cellNameTf.getText().equals("Komórka  (np. B3)")) {
                    cellNameTf.setText("");
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if(cellNameTf.getText().isEmpty()) {
                    cellNameTf.setText("Komórka  (np. B3)");
                }
            }
        });



        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel2ActionPerformed

    }//GEN-LAST:event_buttonPanel2ActionPerformed

    private void buttonPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel3ActionPerformed

    }//GEN-LAST:event_buttonPanel3ActionPerformed

    private void buttonPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel1ActionPerformed

    }//GEN-LAST:event_buttonPanel1ActionPerformed

    private void buttonPanel1MousePressed(java.awt.event.MouseEvent evt) {
        cardLayout.show(background1, "2 1");
    }

    private void buttonPanel2MousePressed(java.awt.event.MouseEvent evt) {
        cardLayout.show(background1, "2 2");
    }

    private void buttonPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPanel1MousePressed
        cardLayout.show(background1, "2 3");
    }//GEN-LAST:event_buttonPanel1MousePressed

    private void selectInvoiceFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInvoiceFileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectInvoiceFileButtonActionPerformed

    private void selectInvoiceNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectInvoiceNameTextFieldFocusGained
        if(selectInvoiceNameTextField.getText().equals("Nazwa Szablonu")) {
            selectInvoiceNameTextField.setText("");
        }
    }//GEN-LAST:event_selectInvoiceNameTextFieldFocusGained

    private void selectInvoiceNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectInvoiceNameTextFieldFocusLost
        if(selectInvoiceNameTextField.getText().isEmpty()) {
            selectInvoiceNameTextField.setText("Nazwa Szablonu");
        }
    }//GEN-LAST:event_selectInvoiceNameTextFieldFocusLost

    private void selectInvoiceNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInvoiceNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectInvoiceNameTextFieldActionPerformed

    private void parameterNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parameterNameTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterNameTfFocusGained

    private void parameterNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parameterNameTfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterNameTfFocusLost

    private void parameterNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameterNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterNameTfActionPerformed

    private void cellNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNameTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cellNameTfFocusGained

    private void cellNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNameTfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cellNameTfFocusLost

    private void addNewParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewParameterButtonActionPerformed

        String paramName = parameterNameTf.getText();
        if(paramName.isEmpty() || paramName.equals("Nazwa parametru")){
            JOptionPane.showMessageDialog(this, "Podaj nazwę parametru");
            return;
        }

        String cellName = cellNameTf.getText();
        if(cellName.isEmpty() || cellName.equals("Komórka  (np. B3)")){
            JOptionPane.showMessageDialog(this, "Podaj nazwę komórki");
            return;
        }

        String entrySubstring = entrySubstringTf.getText();
        if(entrySubstring.isEmpty() || entrySubstring.equals("Aby otoczyć wartość tekstem, zapisz ją jako @ (np. tekst @ tekst)")){
            entrySubstring = "";
        }

        String textAlignment = textAlignmentCombo.getSelectedItem().toString();
        textAlignment = switch (textAlignment) {
            case "Środek" -> "C";
            case "Prawo" -> "R";
            default -> "L";
        };

        String autoParam = autoParamChoice.getSelectedItem().toString();
        autoParam = switch (autoParam) {
            case "Numer" -> "N";
            case "Data" -> "D";
            case "Blok Tekstu" -> "L";
            case "Cena - Całkowita" -> "T";
            case "Cena - Ile sztuk" -> "Q";
            case "Cena - Jednostkowa" -> "U";
            case "Cena - Słownie" -> "S";
            case "Dopełnianie" -> "F";
            default -> ".";
        };


        String data = paramName + ";" + cellName + ";" + entrySubstring + ";" + textAlignment + ";" + autoParam;
        paramCellCombo.addItem(data);
        paramCellCombo.setSelectedIndex(paramCellCombo.getItemCount()-1);

        resetInvoiceConfigForm();




    }//GEN-LAST:event_addNewParameterButtonActionPerformed

    private void resetInvoiceConfigForm(){
        parameterNameTf.setText("Nazwa parametru");
        cellNameTf.setText("Komórka  (np. B3)");
        entrySubstringTf.setText("Aby otoczyć wartość tekstem, zapisz ją jako @ (np. tekst @ tekst)");
        textAlignmentCombo.setSelectedIndex(0);
        autoParamChoice.setSelectedIndex(0);
    }

    private void paramCellComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramCellComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paramCellComboActionPerformed

    private void saveFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveFormActionPerformed

    private void deleteParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteParameterButtonActionPerformed
        int index = paramCellCombo.getSelectedIndex();
        if(index != -1){
            paramCellCombo.removeItemAt(index);
        }

    }//GEN-LAST:event_deleteParameterButtonActionPerformed

    private void autoParamChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoParamChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoParamChoiceActionPerformed

    private void textAlignmentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlignmentComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlignmentComboActionPerformed

    private void entrySubstringTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySubstringTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySubstringTfFocusGained

    private void entrySubstringTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySubstringTfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySubstringTfFocusLost

    private void entrySubstringTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrySubstringTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySubstringTfActionPerformed

    private void proceedToTemplateConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedToTemplateConfigurationButtonActionPerformed
        parameterNameTf.setText("Nazwa parametru");
        cellNameTf.setText("Komórka  (np. B3)");
        entrySubstringTf.setText("Aby otoczyć wartość tekstem, zapisz ją jako @ (np. tekst @ tekst)");
        textAlignmentCombo.setSelectedIndex(0);
        autoParamChoice.setSelectedIndex(0);
        paramCellCombo.removeAllItems();
    }//GEN-LAST:event_proceedToTemplateConfigurationButtonActionPerformed

    private void fillInvoiceGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_
        // GenerateButtonActionPerformed

    }//GEN-LAST:event_fillInvoiceGenerateButtonActionPerformed

    private void cellNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellNameTfActionPerformed

    private void invoiceButtonPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceButtonPanel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceButtonPanel3ActionPerformed

    private void suggestionsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestionsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suggestionsComboBoxActionPerformed

    private void controllJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_controllJButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_controllJButton1ActionPerformed

    private void initCardLayout(){
        background1.remove(dashBoardPanelCard);
        background1.remove(archiveMenuCard);
        background1.remove(remeberedPhrasesCard);
        background1.remove(fillFormCard);
        background1.remove(selectInvoiceFileCard);
        background1.remove(fillInvoiceDataCard);
        background1.remove(choseInvoiceCard);
        background1.remove(savedInvoiceBlueprintCards);
        background1.remove(lastInvoicesCard);


        background1.add(dashBoardPanelCard, "0 0");
        background1.add(choseInvoiceCard, "1 1");
        background1.add(fillInvoiceDataCard, "fillInvoiceDataCard");

        background1.add(selectInvoiceFileCard, "1 2");
        background1.add(fillFormCard, "fillFormCard");

        background1.add(archiveMenuCard, "2 0");

        background1.add(lastInvoicesCard, "2 1");
        background1.add(remeberedPhrasesCard, "2 2");
        background1.add(savedInvoiceBlueprintCards, "2 3");

        buttonPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardLayout.show(background1, "2 1");
            }
        });

        buttonPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardLayout.show(background1, "2 2");
            }
        });

        buttonPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardLayout.show(background1, "2 3");
            }
        });

    }






    public RoundedInfoPanel getDashBoardChartDisplayPanel() {
        return dashboardChartDisplayPanel;
    }
    public JProgressBar getYearlyIncomeProgressBar() {
        return yearlyIncomeProgressBar;
    }
    public JLabel getIncomeThisMonthLabel() {
        return incomeThisMonthLabel;
    }
    public JLabel getThisMonthsTargetLabel() {
        return thisMonthsTargetLabel;
    }
    public JLabel getThisMonthInvoiceCountLabel() {
        return thisMonthInvoiceCountLabel;
    }
    public JPanel getDashBoardPanelCard() {return dashBoardPanelCard;}
    public CardLayout getCardLayout() {
        return cardLayout;
    }
    public JTextField getInvoiceNameField() {
        return selectInvoiceNameTextField;
    }
    public JButton getChoseFileButton() {
        return selectInvoiceFileButton;
    }
    public JButton getProceedButton() {
        return proceedToTemplateConfigurationButton;
    }
    public JComboBox<String> getParamCellCombo() {
        return paramCellCombo;
    }
    public JButton getSaveFormButton() {
        return saveForm;
    }
    public JPanel getBackgroundPanel() {
        return background1;
    }
    public JPanel getChoseInvoiceDisplayPanel() {
        return choseInvoiceDisplayPanel;
    }
    public Menu getMenu() {
        return menu1;
    }
    public JPanel getInvoiceDataRenderPanel() {
        return fillInvoiceDataRenderPanel;
    }




//    private InvoiceGenerator invoiceGenerator;
    private ConfigStorage configStorage;
    private Map<String, WorkingInvoice> invoiceCollection;
    private InvoiceBlueprintAdder invoiceAdder;
    private CardLayout cardLayout;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewParameterButton;
    private javax.swing.JPanel archiveMenuCard;
    private javax.swing.JComboBox<String> autoParamChoice;
    private com.woytuloo.accountingapp.component.Background background1;
    private javax.swing.JPanel blueprintsChoice;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel1;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel2;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel3;
    private javax.swing.JTextField cellNameTf;
    private javax.swing.JPanel choseInvoiceCard;
    private javax.swing.JPanel choseInvoiceDisplayPanel;
    private com.woytuloo.accountingapp.component.ControllJButton controllJButton1;
    private com.woytuloo.accountingapp.component.ControllJButtonMinimize controllJButtonMinimize1;
    private com.woytuloo.accountingapp.component.CustomScrollpane customScrollpane2;
    private javax.swing.JPanel dashBoardPanelCard;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel dashboardChartDisplayPanel;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel2 dashboardInfoDataPanel;
    private javax.swing.JButton deleteParameterButton;
    private javax.swing.JButton deleteSavedAutoFillCellButton;
    private javax.swing.JButton editSavedAutoFillCellButton;
    private javax.swing.JTextField entrySubstringTf;
    private javax.swing.JPanel fillFormCard;
    private javax.swing.JPanel fillInvoiceDataCard;
    private javax.swing.JPanel fillInvoiceDataRenderPanel;
    private javax.swing.JButton fillInvoiceGenerateButton;
    private javax.swing.JLabel incomeThisMonthLabel;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel3 incomeThisMonthPanel;
    private com.woytuloo.accountingapp.component.InvoiceDataTile invoiceDataTile1;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel3 invoicesThisMonthPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel lastInvoicesCard;
    private javax.swing.JPanel lastInvoicesChoice;
    private javax.swing.JPanel lastInvoicesRenderPanel;
    private javax.swing.JTextField lastInvoicesSearchBar;
    private javax.swing.JButton lastInvoicesSearchButton;
    private com.woytuloo.accountingapp.menu.Menu menu1;
    private com.woytuloo.accountingapp.component.mvPanel mvPanel1;
    private javax.swing.JComboBox<String> paramCellCombo;
    private javax.swing.JTextField parameterNameTf;
    private javax.swing.JButton proceedToTemplateConfigurationButton;
    private javax.swing.JPanel registryChoice;
    private javax.swing.JPanel remeberedPhrasesCard;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel3 roundedInfoPanel34;
    private com.woytuloo.accountingapp.component.RoundedTile roundedTile1;
    private com.woytuloo.accountingapp.component.RoundedTile roundedTile2;
    private com.woytuloo.accountingapp.component.RoundedTile roundedTile3;
    private com.woytuloo.accountingapp.component.RoundedTile roundedTile4;
    private javax.swing.JButton saveForm;
    private javax.swing.JPanel savedInvoiceBlueprintCards;
    private javax.swing.JPanel savedInvoiceBlueprintDisplayPanel;
    private javax.swing.JButton selectInvoiceFileButton;
    private javax.swing.JPanel selectInvoiceFileCard;
    private javax.swing.JTextField selectInvoiceNameTextField;
    private javax.swing.JComboBox<String> suggestionsComboBox;
    private javax.swing.JTextArea suggestionsDisplayTextArea;
    private javax.swing.JComboBox<String> textAlignmentCombo;
    private javax.swing.JLabel thisMonthInvoiceCountLabel;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel3 thisMonthlyTargetPanel;
    private javax.swing.JLabel thisMonthsTargetLabel;
    private com.woytuloo.accountingapp.component.TopMvPanelPlusButtons topMvPanelPlusButtons1;
    private javax.swing.JProgressBar yearlyIncomeProgressBar;

    public ControllJButton getExitButton() {
        return controllJButton1;
    }

    public JButton getGenerateInvoiceButton() {
        return fillInvoiceGenerateButton;
    }

    public JPanel getRememberedJPanel() {
        return remeberedPhrasesCard;
    }

    public JComboBox getParametersCombo() {
        return suggestionsComboBox;
    }

    public JTextArea getSuggestionsTextArea() {
        return suggestionsDisplayTextArea;
    }

    public JButton getSaveButton() {
        return editSavedAutoFillCellButton;
    }

    public JButton getDeleteButton() {
        return deleteSavedAutoFillCellButton;
    }

    public JPanel getLastInvoiceRenderPanel() {
        return lastInvoicesRenderPanel;
    }

    public ButtonPanel showLastInvoicesButtonPanel() {
        return buttonPanel1;
    }

    public JButton getSearchButton() {
        return lastInvoicesSearchButton;
    }

    public JTextField getSearchTextField() {
        return lastInvoicesSearchBar;
    }

    public JPanel getSavedBlueprintsCard() {
        return savedInvoiceBlueprintCards;
    }

    public JPanel getSavedBlueprintsDisplayPanel() {
        return savedInvoiceBlueprintDisplayPanel;
    }

    // End of variables declaration//GEN-END:variables
}