/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.woytuloo.accountingapp.main;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.woytuloo.accountingapp.InvoiceManagement.Invoice;
import com.woytuloo.accountingapp.InvoiceManagement.InvoiceBlueprintAdder;
import com.woytuloo.accountingapp.InvoiceManagement.InvoiceGenerator;
import com.woytuloo.accountingapp.charts.ChartsGenerator;
import com.woytuloo.accountingapp.config.ConfigStorage;
import com.woytuloo.accountingapp.menu.MenuEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.geom.RoundRectangle2D;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author wojte
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        FlatDarculaLaf.setup();
        SwingUtilities.updateComponentTreeUI(this);
           
        
        initComponents();
        menu1.setEvent( new MenuEvent(){
            @Override
            public void selected(int index, int subIndex){
                    String indexStr = index + " " + subIndex;
                    cardLayout.show(background1,  indexStr);      
                System.out.println(index + " " + subIndex);
            }
        });
        this.setShape(new RoundRectangle2D.Double(0, 0, 1409, 840, 15, 15));
        mvPanel1.initMv(this);
        topMvPanelPlusButtons1.initMv(this);
        invoiceCollection = new HashMap<>();
        configStorage = new ConfigStorage();
        configStorage.loadConfigFile();
        loadInvoices();
        ChartsGenerator.showIncomeChart(roundedInfoPanel1.getIncomeChart());
        ChartsGenerator.showWorkDoneChart(roundedInfoPanel1.getWorkDoneChart());
        initCardLayout();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customScrollpane2 = new com.woytuloo.accountingapp.component.CustomScrollpane();
        menu1 = new com.woytuloo.accountingapp.menu.Menu();
        mvPanel1 = new com.woytuloo.accountingapp.component.mvPanel();
        topMvPanelPlusButtons1 = new com.woytuloo.accountingapp.component.TopMvPanelPlusButtons();
        controllJButton1 = new com.woytuloo.accountingapp.component.ControllJButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        background1 = new com.woytuloo.accountingapp.component.Background();
        newInvoice = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paramValueTable = new javax.swing.JTable();
        generateInvoice = new javax.swing.JButton();
        invoiceChoiceCombo = new javax.swing.JComboBox<>();
        dashBoardPanel = new javax.swing.JPanel();
        roundedInfoPanel1 = new com.woytuloo.accountingapp.component.RoundedInfoPanel();
        roundedInfoPanel21 = new com.woytuloo.accountingapp.component.RoundedInfoPanel2(new java.awt.Color(20, 20, 20));
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        roundedInfoPanel22 = new com.woytuloo.accountingapp.component.RoundedInfoPanel2(new Color(51,71,176));
        roundedInfoPanel23 = new com.woytuloo.accountingapp.component.RoundedInfoPanel2(new Color(51,71,176));
        roundedInfoPanel24 = new com.woytuloo.accountingapp.component.RoundedInfoPanel2(new Color(51,71,176));
        addNewForm = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        chooseNewBlueprint = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        blueprintNametf = new javax.swing.JTextField();
        parameterNameTf = new javax.swing.JTextField();
        cellNameTf = new javax.swing.JTextField();
        addNewParameterButton = new javax.swing.JButton();
        paramCellCombo = new javax.swing.JComboBox<>();
        saveForm = new javax.swing.JButton();
        deleteParameterButton = new javax.swing.JButton();
        autoParamChoice = new javax.swing.JComboBox<>();
        textAlignmentCombo = new javax.swing.JComboBox<>();
        entrySubstringTf = new javax.swing.JTextField();
        archiveMenuCard = new javax.swing.JPanel();
        lastInvoicesChoice = new javax.swing.JPanel();
        buttonPanel1 = new com.woytuloo.accountingapp.component.ButtonPanel();
        registryChoice = new javax.swing.JPanel();
        buttonPanel2 = new com.woytuloo.accountingapp.component.ButtonPanel();
        blueprintsChoice = new javax.swing.JPanel();
        buttonPanel3 = new com.woytuloo.accountingapp.component.ButtonPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 20));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));

        menu1.setBackground(new java.awt.Color(20, 20, 20));
        customScrollpane2.setViewportView(menu1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(customScrollpane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mvPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customScrollpane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );

        topMvPanelPlusButtons1.setBackground(new java.awt.Color(15, 15, 15));

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel1.setText("InvoiceHollow");

        javax.swing.GroupLayout topMvPanelPlusButtons1Layout = new javax.swing.GroupLayout(topMvPanelPlusButtons1);
        topMvPanelPlusButtons1.setLayout(topMvPanelPlusButtons1Layout);
        topMvPanelPlusButtons1Layout.setHorizontalGroup(
            topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topMvPanelPlusButtons1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(controllJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topMvPanelPlusButtons1Layout.setVerticalGroup(
            topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controllJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(topMvPanelPlusButtons1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1))
        );

        jPanel2.setBackground(new java.awt.Color(15, 15, 15));

        background1.setOpaque(true);
        cardLayout = new CardLayout();
        background1.setLayout(new java.awt.CardLayout());
        background1.setLayout(cardLayout);

        newInvoice.setOpaque(false);

        paramValueTable.setBackground(new java.awt.Color(51, 51, 51));
        paramValueTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paramValueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Parametr", "Wartość"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        paramValueTable.setRowHeight(40);
        jScrollPane2.setViewportView(paramValueTable);

        generateInvoice.setBackground(new java.awt.Color(51, 51, 51));
        generateInvoice.setText("Generuj");
        generateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateInvoiceActionPerformed(evt);
            }
        });

        invoiceChoiceCombo.setBackground(new java.awt.Color(51, 51, 51));
        invoiceChoiceCombo.setMaximumRowCount(10);
        invoiceChoiceCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceChoiceComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newInvoiceLayout = new javax.swing.GroupLayout(newInvoice);
        newInvoice.setLayout(newInvoiceLayout);
        newInvoiceLayout.setHorizontalGroup(
            newInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInvoiceLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(newInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceChoiceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        newInvoiceLayout.setVerticalGroup(
            newInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInvoiceLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(invoiceChoiceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(generateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        background1.add(newInvoice, "card5");

        dashBoardPanel.setForeground(new java.awt.Color(255, 255, 255));
        dashBoardPanel.setOpaque(false);

        roundedInfoPanel1.setBackground(new java.awt.Color(255, 0, 102));

        roundedInfoPanel21.setBackground(new java.awt.Color(20, 20, 20));

        jProgressBar1.setBackground(new java.awt.Color(102, 102, 102));
        jProgressBar1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(51, 196, 32));
        jProgressBar1.setMaximum(200000);
        jProgressBar1.setValue(40000);
        jProgressBar1.setStringPainted(true);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Podsumowanie");

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(970, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        roundedInfoPanel22.setBackground(new Color(51,102,255));

        javax.swing.GroupLayout roundedInfoPanel22Layout = new javax.swing.GroupLayout(roundedInfoPanel22);
        roundedInfoPanel22.setLayout(roundedInfoPanel22Layout);
        roundedInfoPanel22Layout.setHorizontalGroup(
            roundedInfoPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        roundedInfoPanel22Layout.setVerticalGroup(
            roundedInfoPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        roundedInfoPanel23.setBackground(new java.awt.Color(51, 71, 176));

        javax.swing.GroupLayout roundedInfoPanel23Layout = new javax.swing.GroupLayout(roundedInfoPanel23);
        roundedInfoPanel23.setLayout(roundedInfoPanel23Layout);
        roundedInfoPanel23Layout.setHorizontalGroup(
            roundedInfoPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        roundedInfoPanel23Layout.setVerticalGroup(
            roundedInfoPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout roundedInfoPanel24Layout = new javax.swing.GroupLayout(roundedInfoPanel24);
        roundedInfoPanel24.setLayout(roundedInfoPanel24Layout);
        roundedInfoPanel24Layout.setHorizontalGroup(
            roundedInfoPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        roundedInfoPanel24Layout.setVerticalGroup(
            roundedInfoPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout roundedInfoPanel21Layout = new javax.swing.GroupLayout(roundedInfoPanel21);
        roundedInfoPanel21.setLayout(roundedInfoPanel21Layout);
        roundedInfoPanel21Layout.setHorizontalGroup(
            roundedInfoPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedInfoPanel21Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(roundedInfoPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedInfoPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(roundedInfoPanel21Layout.createSequentialGroup()
                            .addComponent(roundedInfoPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(roundedInfoPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(roundedInfoPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedInfoPanel21Layout.setVerticalGroup(
            roundedInfoPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedInfoPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundedInfoPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roundedInfoPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundedInfoPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundedInfoPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout dashBoardPanelLayout = new javax.swing.GroupLayout(dashBoardPanel);
        dashBoardPanel.setLayout(dashBoardPanelLayout);
        dashBoardPanelLayout.setHorizontalGroup(
            dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundedInfoPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roundedInfoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1193, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashBoardPanelLayout.setVerticalGroup(
            dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(roundedInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundedInfoPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        background1.add(dashBoardPanel, "card2");

        addNewForm.setOpaque(false);

        jPanel5.setBackground(new java.awt.Color(20, 20, 20));

        chooseNewBlueprint.setBackground(new java.awt.Color(51, 51, 51));
        chooseNewBlueprint.setText("Wybierz plik");
        chooseNewBlueprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseNewBlueprintActionPerformed(evt);
            }
        });

        fileNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        blueprintNametf.setBackground(new java.awt.Color(51, 51, 51));
        blueprintNametf.setText("Nazwa Szablonu");
        blueprintNametf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                blueprintNametfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                blueprintNametfFocusLost(evt);
            }
        });
        blueprintNametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueprintNametfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blueprintNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(fileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chooseNewBlueprint, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blueprintNametf)
                    .addComponent(chooseNewBlueprint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(fileNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        parameterNameTf.setBackground(new java.awt.Color(51, 51, 51));
        parameterNameTf.setText("Nazwa parametru");
        parameterNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                parameterNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                parameterNameTfFocusLost(evt);
            }
        });
        parameterNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameterNameTfActionPerformed(evt);
            }
        });

        cellNameTf.setBackground(new java.awt.Color(51, 51, 51));
        cellNameTf.setText("Komórka  (np. B3)");
        cellNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cellNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cellNameTfFocusLost(evt);
            }
        });

        addNewParameterButton.setBackground(new java.awt.Color(51, 51, 51));
        addNewParameterButton.setText("Dodaj");
        addNewParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewParameterButtonActionPerformed(evt);
            }
        });

        paramCellCombo.setBackground(new java.awt.Color(51, 51, 51));
        paramCellCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramCellComboActionPerformed(evt);
            }
        });

        saveForm.setBackground(new java.awt.Color(51, 51, 51));
        saveForm.setText("Zapisz Szablon");
        saveForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFormActionPerformed(evt);
            }
        });

        deleteParameterButton.setBackground(new java.awt.Color(51, 51, 51));
        deleteParameterButton.setText("Usuń");
        deleteParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteParameterButtonActionPerformed(evt);
            }
        });

        autoParamChoice.setBackground(new java.awt.Color(51, 51, 51));
        autoParamChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Automatyzuj>", "Numer", "Data", "Cena - Całkowita", "Cena - Ile sztuk", "Cena - Jednostkowa", "Cena - Słownie" }));
        autoParamChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoParamChoiceActionPerformed(evt);
            }
        });

        textAlignmentCombo.setBackground(new java.awt.Color(51, 51, 51));
        textAlignmentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Pozycja w komórce>", "Lewo", "Środek", "Prawo" }));
        textAlignmentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlignmentComboActionPerformed(evt);
            }
        });

        entrySubstringTf.setBackground(new java.awt.Color(51, 51, 51));
        entrySubstringTf.setText("Wartość stała");
        entrySubstringTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entrySubstringTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entrySubstringTfFocusLost(evt);
            }
        });
        entrySubstringTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrySubstringTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewFormLayout = new javax.swing.GroupLayout(addNewForm);
        addNewForm.setLayout(addNewFormLayout);
        addNewFormLayout.setHorizontalGroup(
            addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewFormLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewFormLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(autoParamChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addNewFormLayout.createSequentialGroup()
                        .addComponent(entrySubstringTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addNewParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addNewFormLayout.createSequentialGroup()
                        .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parameterNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addNewFormLayout.createSequentialGroup()
                                .addComponent(paramCellCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deleteParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cellNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(saveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textAlignmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140))
        );
        addNewFormLayout.setVerticalGroup(
            addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewFormLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parameterNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoParamChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAlignmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entrySubstringTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramCellCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(deleteParameterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addComponent(saveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        background1.add(addNewForm, "card4");

        archiveMenuCard.setOpaque(false);

        lastInvoicesChoice.setBackground(new java.awt.Color(0, 153, 204));
        lastInvoicesChoice.setOpaque(false);

        buttonPanel1.setBorder(null);
        ImageIcon iconInvoice = new ImageIcon (getClass().getResource("/Images/lastinvoicesIcon.png"));
        Image imgInvoice = iconInvoice.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel1.setIcon(new ImageIcon(imgInvoice));
        buttonPanel1.setText("Ostatnie Faktury");
        buttonPanel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonPanel1MouseReleased(evt);
            }
        });
        buttonPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lastInvoicesChoiceLayout = new javax.swing.GroupLayout(lastInvoicesChoice);
        lastInvoicesChoice.setLayout(lastInvoicesChoiceLayout);
        lastInvoicesChoiceLayout.setHorizontalGroup(
            lastInvoicesChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        lastInvoicesChoiceLayout.setVerticalGroup(
            lastInvoicesChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        registryChoice.setBackground(new java.awt.Color(153, 153, 255));
        registryChoice.setOpaque(false);

        ImageIcon iconReg = new ImageIcon (getClass().getResource("/Images/registryIcon.png"));
        Image imgReg = iconReg.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel2.setIcon(new javax.swing.ImageIcon(imgReg));
        buttonPanel2.setText("Spis podpowiedzi");
        buttonPanel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registryChoiceLayout = new javax.swing.GroupLayout(registryChoice);
        registryChoice.setLayout(registryChoiceLayout);
        registryChoiceLayout.setHorizontalGroup(
            registryChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        registryChoiceLayout.setVerticalGroup(
            registryChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        blueprintsChoice.setBackground(new java.awt.Color(255, 153, 204));
        blueprintsChoice.setOpaque(false);

        ImageIcon iconBp = new ImageIcon (getClass().getResource("/Images/blueprintsIcon.png"));
        Image imgBp = iconBp.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel3.setIcon(new javax.swing.ImageIcon(imgBp));
        buttonPanel3.setText("Szablony");
        buttonPanel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blueprintsChoiceLayout = new javax.swing.GroupLayout(blueprintsChoice);
        blueprintsChoice.setLayout(blueprintsChoiceLayout);
        blueprintsChoiceLayout.setHorizontalGroup(
            blueprintsChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blueprintsChoiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        blueprintsChoiceLayout.setVerticalGroup(
            blueprintsChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout archiveMenuCardLayout = new javax.swing.GroupLayout(archiveMenuCard);
        archiveMenuCard.setLayout(archiveMenuCardLayout);
        archiveMenuCardLayout.setHorizontalGroup(
            archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveMenuCardLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lastInvoicesChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(registryChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(blueprintsChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        archiveMenuCardLayout.setVerticalGroup(
            archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveMenuCardLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastInvoicesChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registryChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueprintsChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        background1.add(archiveMenuCard, "card4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1209, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 1203, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(topMvPanelPlusButtons1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topMvPanelPlusButtons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPanel2ActionPerformed

    private void chooseNewBlueprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseNewBlueprintActionPerformed
        this.invoiceAdder = new InvoiceBlueprintAdder(fileNameLabel, invoiceCollection);
        invoiceAdder.addNewBlueprint();
        
    }//GEN-LAST:event_chooseNewBlueprintActionPerformed

    private void parameterNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameterNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterNameTfActionPerformed

    private void addNewParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewParameterButtonActionPerformed
        if(!cellNameTf.getText().isEmpty() && !parameterNameTf.getText().isEmpty()){

            String paramCell = parameterNameTf.getText() + ":" + cellNameTf.getText();

            
            
            String[] automations = {"","N","D", "CC", "CI", "CJ", "CS"};      
            paramCell += ":" + automations[autoParamChoice.getSelectedIndex()];

            
            String[] alignments = {"L", "L", "C", "R"};
            paramCell += ":" + alignments[textAlignmentCombo.getSelectedIndex()];
            String constVal = entrySubstringTf.getText();
            paramCell += ":";
            
            if(constVal.equals("Wartość stała")){
                paramCell += constVal;
            }
            
            
            boolean found = false;
            for(int i=0; i < paramCellCombo.getItemCount(); i++){
                if(paramCellCombo.getItemAt(i).equals(paramCell))
                    found = true;
            }
            if(!found)
                paramCellCombo.addItem(paramCell);
                paramCellCombo.setSelectedIndex(paramCellCombo.getItemCount()-1);
            
            
        }
    }//GEN-LAST:event_addNewParameterButtonActionPerformed

    private void saveFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFormActionPerformed
        if(!blueprintNametf.getText().equals("Nazwa Szablonu"))
            new JOptionPane().setVisible(true);
        
        Map<String, String> cellMap= new HashMap<>();
        Map<String, String> paramAutoMap= new HashMap<>();   
        Map<String, String> cellAlignMap = new HashMap<>();
        
        
        for(int i=0;i<paramCellCombo.getItemCount(); i++){
            String[] params = paramCellCombo.getItemAt(i).split(":");
            cellMap.put(params[0], params[1]);                       // nazwa - komorka          
            paramAutoMap.put(params[0], params[2]);                  // nazwa - ktora automatyzacja
            cellAlignMap.put(params[1], params[3]);                  // komorka = alignment
            
        }
        
        
        invoiceAdder.fillCollection(blueprintNametf.getText(), cellMap, paramAutoMap, cellAlignMap);
        reloadChoiceCombo();


    }//GEN-LAST:event_saveFormActionPerformed

    private void paramCellComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramCellComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paramCellComboActionPerformed

    private void blueprintNametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueprintNametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueprintNametfActionPerformed

    private void deleteParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteParameterButtonActionPerformed
        Object obj = paramCellCombo.getSelectedItem();
        if(obj != null)
            paramCellCombo.removeItem(obj); 
    }//GEN-LAST:event_deleteParameterButtonActionPerformed

    private void parameterNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parameterNameTfFocusGained
        if(this.parameterNameTf.getText().equals("Nazwa parametru"))
            this.parameterNameTf.setText("");
    }//GEN-LAST:event_parameterNameTfFocusGained

    private void parameterNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parameterNameTfFocusLost
        if(parameterNameTf.getText().equals(""))
            this.parameterNameTf.setText("Nazwa parametru");
    }//GEN-LAST:event_parameterNameTfFocusLost

    private void cellNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNameTfFocusLost
        if(cellNameTf.getText().equals(""))
            this.cellNameTf.setText("Komórka  (np. B3)");
    }//GEN-LAST:event_cellNameTfFocusLost

    private void cellNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNameTfFocusGained
        if(this.cellNameTf.getText().equals("Komórka  (np. B3)"))
            this.cellNameTf.setText("");
    }//GEN-LAST:event_cellNameTfFocusGained

    private void buttonPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPanel3ActionPerformed

    private void blueprintNametfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_blueprintNametfFocusGained
        if(this.blueprintNametf.getText().equals("Nazwa Szablonu"))
            this.blueprintNametf.setText("");
    }//GEN-LAST:event_blueprintNametfFocusGained

    private void blueprintNametfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_blueprintNametfFocusLost
        if(blueprintNametf.getText().equals(""))
            this.blueprintNametf.setText("Nazwa Szablonu");
    }//GEN-LAST:event_blueprintNametfFocusLost

    private void buttonPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPanel1ActionPerformed

    private void buttonPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPanel1MousePressed
        //buttonPanel1.clickedColor();
    }//GEN-LAST:event_buttonPanel1MousePressed

    private void buttonPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPanel1MouseReleased
        //buttonPanel1.releasedColor();
    }//GEN-LAST:event_buttonPanel1MouseReleased

    private void invoiceChoiceComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceChoiceComboActionPerformed
        String inName = invoiceChoiceCombo.getItemAt(invoiceChoiceCombo.getSelectedIndex());
        if(inName == null || inName.equals(""))
            return;
        this.invoiceGenerator = new InvoiceGenerator(invoiceCollection.get(inName), paramValueTable, configStorage);
        invoiceGenerator.fillTable();
        
        
    }//GEN-LAST:event_invoiceChoiceComboActionPerformed

    private void generateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateInvoiceActionPerformed
        invoiceGenerator.generateInvoice();
        
        
    }//GEN-LAST:event_generateInvoiceActionPerformed

    private void autoParamChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoParamChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoParamChoiceActionPerformed

    private void textAlignmentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlignmentComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlignmentComboActionPerformed

    private void entrySubstringTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySubstringTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySubstringTfFocusGained

    private void entrySubstringTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySubstringTfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySubstringTfFocusLost

    private void entrySubstringTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrySubstringTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySubstringTfActionPerformed

    private void loadInvoices(){
        this.invoiceAdder = new InvoiceBlueprintAdder(invoiceCollection);
        reloadChoiceCombo();
    }
    
    private void reloadChoiceCombo(){
        this.invoiceChoiceCombo.removeAllItems();
        this.invoiceChoiceCombo.addItem("");
        this.invoiceCollection.forEach((name,invoice)->{this.invoiceChoiceCombo.addItem(name);});
    }

    private void initCardLayout(){
        background1.remove(dashBoardPanel);
        background1.remove(archiveMenuCard);
        background1.remove(addNewForm);
        background1.remove(newInvoice);

        background1.add(dashBoardPanel, "0 0");
        background1.add(archiveMenuCard, "2 0");
        background1.add(addNewForm, "1 2");
        background1.add(newInvoice, "1 1");
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    private InvoiceGenerator invoiceGenerator;
    private ConfigStorage configStorage;
    private Map<String,Invoice> invoiceCollection;
    private InvoiceBlueprintAdder invoiceAdder;
    private CardLayout cardLayout;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addNewForm;
    private javax.swing.JButton addNewParameterButton;
    private javax.swing.JPanel archiveMenuCard;
    private javax.swing.JComboBox<String> autoParamChoice;
    private com.woytuloo.accountingapp.component.Background background1;
    private javax.swing.JTextField blueprintNametf;
    private javax.swing.JPanel blueprintsChoice;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel1;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel2;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel3;
    private javax.swing.JTextField cellNameTf;
    private javax.swing.JButton chooseNewBlueprint;
    private com.woytuloo.accountingapp.component.ControllJButton controllJButton1;
    private com.woytuloo.accountingapp.component.CustomScrollpane customScrollpane2;
    private javax.swing.JPanel dashBoardPanel;
    private javax.swing.JButton deleteParameterButton;
    private javax.swing.JTextField entrySubstringTf;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JButton generateInvoice;
    private javax.swing.JComboBox<String> invoiceChoiceCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lastInvoicesChoice;
    private com.woytuloo.accountingapp.menu.Menu menu1;
    private com.woytuloo.accountingapp.component.mvPanel mvPanel1;
    private javax.swing.JPanel newInvoice;
    private javax.swing.JComboBox<String> paramCellCombo;
    private javax.swing.JTable paramValueTable;
    private javax.swing.JTextField parameterNameTf;
    private javax.swing.JPanel registryChoice;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel roundedInfoPanel1;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel2 roundedInfoPanel21;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel2 roundedInfoPanel22;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel2 roundedInfoPanel23;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel2 roundedInfoPanel24;
    private javax.swing.JButton saveForm;
    private javax.swing.JComboBox<String> textAlignmentCombo;
    private com.woytuloo.accountingapp.component.TopMvPanelPlusButtons topMvPanelPlusButtons1;
    // End of variables declaration//GEN-END:variables
}
