/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.woytuloo.accountingapp.main;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.woytuloo.accountingapp.InvoiceManagement.Invoice;
import com.woytuloo.accountingapp.InvoiceManagement.InvoiceBlueprintAdder;
import com.woytuloo.accountingapp.InvoiceManagement.InvoiceGenerator;
import com.woytuloo.accountingapp.charts.ChartsGenerator;
import com.woytuloo.accountingapp.config.ConfigStorage;
import com.woytuloo.accountingapp.menu.MenuEvent;
import com.woytuloo.accountingapp.layout.WrapLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.Shape;
import java.awt.geom.Path2D;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author wojte
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
        private Shape createCustomShape(int width, int height) {
        int arcSize = 15; 
        Path2D path = new Path2D.Double();

        path.moveTo(0, arcSize);                      
        path.quadTo(0, 0, arcSize, 0);                
        path.lineTo(width, 0);                        
        path.lineTo(width, height);                   
        path.lineTo(0, height);                      
        path.closePath();                             

        return path;
    }
    
    public Main() {
        FlatDarculaLaf.setup();
        SwingUtilities.updateComponentTreeUI(this);
           
        initComponents();
        menu1.setEvent( new MenuEvent(){
            @Override
            public void selected(int index, int subIndex){
                    String indexStr = index + " " + subIndex;
                    cardLayout.show(background1,  indexStr);      
                System.out.println(index + " " + subIndex);
            }  
        });
        this.setShape(createCustomShape(getWidth(), getHeight()));
        this.setBackground(new Color(0,0,0,0));
        mvPanel1.initMv(this);
        topMvPanelPlusButtons1.initMv(this);
        invoiceCollection = new HashMap<>();
        configStorage = new ConfigStorage();
        configStorage.loadConfigFile();
        loadInvoices();
        ChartsGenerator.showIncomeChart(dashboardChartDisplayPanel.getIncomeChart());
        ChartsGenerator.showWorkDoneChart(dashboardChartDisplayPanel.getWorkDoneChart());
        initCardLayout();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        customScrollpane2 = new com.woytuloo.accountingapp.component.CustomScrollpane();
        menu1 = new com.woytuloo.accountingapp.menu.Menu();
        mvPanel1 = new com.woytuloo.accountingapp.component.mvPanel();
        topMvPanelPlusButtons1 = new com.woytuloo.accountingapp.component.TopMvPanelPlusButtons();
        controllJButton1 = new com.woytuloo.accountingapp.component.ControllJButton();
        jLabel1 = new javax.swing.JLabel();
        controllJButtonMinimize1 = new com.woytuloo.accountingapp.component.ControllJButtonMinimize(this);
        jPanel2 = new javax.swing.JPanel();
        background1 = new com.woytuloo.accountingapp.component.Background();
        lastInvoicesCard = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lastInvoicesRenderPanel = new javax.swing.JPanel();
        invoiceButtonPanel3 = new com.woytuloo.accountingapp.component.InvoiceButtonPanel();
        roundedTile3 = new com.woytuloo.accountingapp.component.RoundedTile();
        lastInvoicesSearchButton = new javax.swing.JButton();
        lastInvoicesSearchBar = new javax.swing.JTextField();
        dashBoardPanelCard = new javax.swing.JPanel();
        dashboardChartDisplayPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel();
        dashboardInfoDataPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel2(new java.awt.Color(20, 20, 20));
        yearlyIncomeProgressBar = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        incomeThisMonthPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel3();
        incomeThisMonthLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        thisMonthlyTargetPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel3();
        jLabel7 = new javax.swing.JLabel();
        thisMonthsTargetLabel = new javax.swing.JLabel();
        invoicesThisMonthPanel = new com.woytuloo.accountingapp.component.RoundedInfoPanel3();
        roundedInfoPanel34 = new com.woytuloo.accountingapp.component.RoundedInfoPanel3();
        jLabel8 = new javax.swing.JLabel();
        thisMonthInvoiceCountLabel = new javax.swing.JLabel();
        archiveMenuCard = new javax.swing.JPanel();
        lastInvoicesChoice = new javax.swing.JPanel();
        buttonPanel1 = new com.woytuloo.accountingapp.component.ButtonPanel();
        registryChoice = new javax.swing.JPanel();
        buttonPanel2 = new com.woytuloo.accountingapp.component.ButtonPanel();
        blueprintsChoice = new javax.swing.JPanel();
        buttonPanel3 = new com.woytuloo.accountingapp.component.ButtonPanel();
        remeberedPhrasesCard = new javax.swing.JPanel();
        roundedTile4 = new com.woytuloo.accountingapp.component.RoundedTile();
        suggestionsComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        suggestionsDisplayTextArea = new javax.swing.JTextArea();
        deleteSavedAutoFillCellButton = new javax.swing.JButton();
        editSavedAutoFillCellButton = new javax.swing.JButton();
        savedInvoiceBlueprintCards = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        savedInvoiceBlueprintDisplayPanel = new javax.swing.JPanel();
        invoiceButtonPanel2 = new com.woytuloo.accountingapp.component.InvoiceButtonPanel();
        fillInvoiceDataCard = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        fillInvoiceDataRenderPanel = new javax.swing.JPanel();
        invoiceDataTile1 = new com.woytuloo.accountingapp.component.InvoiceDataTile();
        fillInvoiceGenerateButton = new javax.swing.JButton();
        choseInvoiceCard = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        choseInvoiceDisplayPanel = new javax.swing.JPanel();
        invoiceButtonPanel1 = new com.woytuloo.accountingapp.component.InvoiceButtonPanel();
        selectInvoiceFileCard = new javax.swing.JPanel();
        roundedTile1 = new com.woytuloo.accountingapp.component.RoundedTile();
        selectInvoiceNameTextField = new javax.swing.JTextField();
        selectInvoiceFileButton = new javax.swing.JButton();
        proceedToTemplateConfigurationButton = new javax.swing.JButton();
        fillFormCard = new javax.swing.JPanel();
        roundedTile2 = new com.woytuloo.accountingapp.component.RoundedTile();
        parameterNameTf = new javax.swing.JTextField();
        cellNameTf = new javax.swing.JTextField();
        addNewParameterButton = new javax.swing.JButton();
        paramCellCombo = new javax.swing.JComboBox<>();
        saveForm = new javax.swing.JButton();
        autoParamChoice = new javax.swing.JComboBox<>();
        deleteParameterButton = new javax.swing.JButton();
        textAlignmentCombo = new javax.swing.JComboBox<>();
        entrySubstringTf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 20));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(60, 70, 150));

        menu1.setBackground(new java.awt.Color(20, 20, 20));
        customScrollpane2.setViewportView(menu1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(mvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(customScrollpane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mvPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(customScrollpane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        topMvPanelPlusButtons1.setBackground(new java.awt.Color(15, 15, 15));

        jLabel1.setBackground(new java.awt.Color(230, 230, 230));
        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(230, 230, 230));
        jLabel1.setText("InvoiceHollow");

        controllJButtonMinimize1.setBackground(new java.awt.Color(15, 15, 15));
        controllJButtonMinimize1.setForeground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout topMvPanelPlusButtons1Layout = new javax.swing.GroupLayout(topMvPanelPlusButtons1);
        topMvPanelPlusButtons1.setLayout(topMvPanelPlusButtons1Layout);
        topMvPanelPlusButtons1Layout.setHorizontalGroup(
            topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topMvPanelPlusButtons1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(controllJButtonMinimize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(controllJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topMvPanelPlusButtons1Layout.setVerticalGroup(
            topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topMvPanelPlusButtons1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(topMvPanelPlusButtons1Layout.createSequentialGroup()
                .addGroup(topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(controllJButtonMinimize1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(controllJButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setOpaque(false);

        background1.setOpaque(true);
        cardLayout = new CardLayout();
        background1.setLayout(new java.awt.CardLayout());
        background1.setLayout(cardLayout);

        lastInvoicesCard.setOpaque(false);

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setAutoscrolls(true);
        jScrollPane6.setOpaque(false);
        jScrollPane6.setViewportView(null);
        jScrollPane6.getViewport().setOpaque(false);
        jScrollPane6.getVerticalScrollBar().setUnitIncrement(20);

        lastInvoicesRenderPanel.setBackground(new java.awt.Color(204, 0, 51));
        lastInvoicesRenderPanel.setOpaque(false);

        invoiceButtonPanel3.setBackground(new java.awt.Color(255, 0, 51));
        invoiceButtonPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceButtonPanel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lastInvoicesRenderPanelLayout = new javax.swing.GroupLayout(lastInvoicesRenderPanel);
        lastInvoicesRenderPanel.setLayout(lastInvoicesRenderPanelLayout);
        lastInvoicesRenderPanelLayout.setHorizontalGroup(
            lastInvoicesRenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastInvoicesRenderPanelLayout.createSequentialGroup()
                .addComponent(invoiceButtonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 559, Short.MAX_VALUE))
        );
        lastInvoicesRenderPanelLayout.setVerticalGroup(
            lastInvoicesRenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastInvoicesRenderPanelLayout.createSequentialGroup()
                .addComponent(invoiceButtonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 151, Short.MAX_VALUE))
        );

        lastInvoicesRenderPanel.setLayout(new WrapLayout(FlowLayout.LEFT, 30, 30));

        jScrollPane6.setViewportView(lastInvoicesRenderPanel);

        lastInvoicesSearchButton.setBackground(new java.awt.Color(30, 30, 30));
        lastInvoicesSearchButton.setIcon(new ImageIcon(new ImageIcon (getClass().getResource("/Images/searchIcon.png")).getImage().getScaledInstance(30, 30,  java.awt.Image.SCALE_SMOOTH)));
        lastInvoicesSearchButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lastInvoicesSearchBar.setBackground(new java.awt.Color(30, 30, 30));
        lastInvoicesSearchBar.setText("Wyszukaj fakturę  (numer, data, adres)");
        lastInvoicesSearchBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout roundedTile3Layout = new javax.swing.GroupLayout(roundedTile3);
        roundedTile3.setLayout(roundedTile3Layout);
        roundedTile3Layout.setHorizontalGroup(
            roundedTile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedTile3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastInvoicesSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastInvoicesSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roundedTile3Layout.setVerticalGroup(
            roundedTile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedTile3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedTile3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastInvoicesSearchBar)
                    .addComponent(lastInvoicesSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout lastInvoicesCardLayout = new javax.swing.GroupLayout(lastInvoicesCard);
        lastInvoicesCard.setLayout(lastInvoicesCardLayout);
        lastInvoicesCardLayout.setHorizontalGroup(
            lastInvoicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastInvoicesCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lastInvoicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedTile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lastInvoicesCardLayout.setVerticalGroup(
            lastInvoicesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastInvoicesCardLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(roundedTile3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background1.add(lastInvoicesCard, "card5");

        dashBoardPanelCard.setForeground(new java.awt.Color(255, 255, 255));
        dashBoardPanelCard.setOpaque(false);

        dashboardChartDisplayPanel.setBackground(new java.awt.Color(255, 0, 102));

        dashboardInfoDataPanel.setBackground(new java.awt.Color(15, 15, 15));
        dashboardInfoDataPanel.setOpaque(true);

        yearlyIncomeProgressBar.setBackground(new java.awt.Color(102, 102, 102));
        yearlyIncomeProgressBar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        yearlyIncomeProgressBar.setForeground(new java.awt.Color(51, 196, 32));
        yearlyIncomeProgressBar.setMaximum(200000);
        yearlyIncomeProgressBar.setValue(40000);
        yearlyIncomeProgressBar.setString("nigga");
        yearlyIncomeProgressBar.setStringPainted(true);

        jLabel2.setBackground(new java.awt.Color(230, 230, 230));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Podsumowanie");

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(970, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        incomeThisMonthPanel.setPreferredSize(new java.awt.Dimension(360, 244));

        incomeThisMonthLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        incomeThisMonthLabel.setForeground(new java.awt.Color(230, 230, 230));
        incomeThisMonthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeThisMonthLabel.setText("9800 zł");
        incomeThisMonthLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        incomeThisMonthLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(230, 230, 230));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dochód w tym miesiącu:");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout incomeThisMonthPanelLayout = new javax.swing.GroupLayout(incomeThisMonthPanel);
        incomeThisMonthPanel.setLayout(incomeThisMonthPanelLayout);
        incomeThisMonthPanelLayout.setHorizontalGroup(
            incomeThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeThisMonthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(incomeThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(incomeThisMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeThisMonthPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        incomeThisMonthPanelLayout.setVerticalGroup(
            incomeThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, incomeThisMonthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(incomeThisMonthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        thisMonthlyTargetPanel.setPreferredSize(new java.awt.Dimension(360, 244));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(230, 230, 230));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Aktualny miesięczny cel:");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        thisMonthsTargetLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        thisMonthsTargetLabel.setForeground(new java.awt.Color(230, 230, 230));
        thisMonthsTargetLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thisMonthsTargetLabel.setText("32");
        thisMonthsTargetLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        thisMonthsTargetLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout thisMonthlyTargetPanelLayout = new javax.swing.GroupLayout(thisMonthlyTargetPanel);
        thisMonthlyTargetPanel.setLayout(thisMonthlyTargetPanelLayout);
        thisMonthlyTargetPanelLayout.setHorizontalGroup(
            thisMonthlyTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thisMonthlyTargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(thisMonthlyTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thisMonthlyTargetPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(thisMonthsTargetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        thisMonthlyTargetPanelLayout.setVerticalGroup(
            thisMonthlyTargetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thisMonthlyTargetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thisMonthsTargetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        roundedInfoPanel34.setPreferredSize(new java.awt.Dimension(360, 244));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(230, 230, 230));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Faktury w tym miesiącu:");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        thisMonthInvoiceCountLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        thisMonthInvoiceCountLabel.setForeground(new java.awt.Color(230, 230, 230));
        thisMonthInvoiceCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thisMonthInvoiceCountLabel.setText("23");
        thisMonthInvoiceCountLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        thisMonthInvoiceCountLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout roundedInfoPanel34Layout = new javax.swing.GroupLayout(roundedInfoPanel34);
        roundedInfoPanel34.setLayout(roundedInfoPanel34Layout);
        roundedInfoPanel34Layout.setHorizontalGroup(
            roundedInfoPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedInfoPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedInfoPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedInfoPanel34Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(thisMonthInvoiceCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        roundedInfoPanel34Layout.setVerticalGroup(
            roundedInfoPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedInfoPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(thisMonthInvoiceCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout invoicesThisMonthPanelLayout = new javax.swing.GroupLayout(invoicesThisMonthPanel);
        invoicesThisMonthPanel.setLayout(invoicesThisMonthPanelLayout);
        invoicesThisMonthPanelLayout.setHorizontalGroup(
            invoicesThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
            .addGroup(invoicesThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(invoicesThisMonthPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(roundedInfoPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        invoicesThisMonthPanelLayout.setVerticalGroup(
            invoicesThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(invoicesThisMonthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(invoicesThisMonthPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(roundedInfoPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout dashboardInfoDataPanelLayout = new javax.swing.GroupLayout(dashboardInfoDataPanel);
        dashboardInfoDataPanel.setLayout(dashboardInfoDataPanelLayout);
        dashboardInfoDataPanelLayout.setHorizontalGroup(
            dashboardInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardInfoDataPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(dashboardInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearlyIncomeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashboardInfoDataPanelLayout.createSequentialGroup()
                        .addComponent(invoicesThisMonthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(incomeThisMonthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thisMonthlyTargetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dashboardInfoDataPanelLayout.setVerticalGroup(
            dashboardInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardInfoDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dashboardInfoDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(thisMonthlyTargetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(incomeThisMonthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(invoicesThisMonthPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(yearlyIncomeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout dashBoardPanelCardLayout = new javax.swing.GroupLayout(dashBoardPanelCard);
        dashBoardPanelCard.setLayout(dashBoardPanelCardLayout);
        dashBoardPanelCardLayout.setHorizontalGroup(
            dashBoardPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardPanelCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashBoardPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashboardInfoDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboardChartDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1202, Short.MAX_VALUE))
                .addContainerGap())
        );
        dashBoardPanelCardLayout.setVerticalGroup(
            dashBoardPanelCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardPanelCardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(dashboardChartDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardInfoDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background1.add(dashBoardPanelCard, "card2");

        archiveMenuCard.setOpaque(false);

        lastInvoicesChoice.setBackground(new java.awt.Color(0, 153, 204));
        lastInvoicesChoice.setOpaque(false);

        buttonPanel1.setBorder(null);
        ImageIcon iconInvoice = new ImageIcon (getClass().getResource("/Images/lastinvoicesIcon.png"));
        Image imgInvoice = iconInvoice.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel1.setIcon(new ImageIcon(imgInvoice));
        buttonPanel1.setText("Ostatnie Faktury");
        buttonPanel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPanel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonPanel1MouseReleased(evt);
            }
        });
        buttonPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lastInvoicesChoiceLayout = new javax.swing.GroupLayout(lastInvoicesChoice);
        lastInvoicesChoice.setLayout(lastInvoicesChoiceLayout);
        lastInvoicesChoiceLayout.setHorizontalGroup(
            lastInvoicesChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        lastInvoicesChoiceLayout.setVerticalGroup(
            lastInvoicesChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        registryChoice.setBackground(new java.awt.Color(153, 153, 255));
        registryChoice.setOpaque(false);

        ImageIcon iconReg = new ImageIcon (getClass().getResource("/Images/registryIcon.png"));
        Image imgReg = iconReg.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel2.setIcon(new javax.swing.ImageIcon(imgReg));
        buttonPanel2.setText("Spis podpowiedzi");
        buttonPanel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPanel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registryChoiceLayout = new javax.swing.GroupLayout(registryChoice);
        registryChoice.setLayout(registryChoiceLayout);
        registryChoiceLayout.setHorizontalGroup(
            registryChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        registryChoiceLayout.setVerticalGroup(
            registryChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        blueprintsChoice.setBackground(new java.awt.Color(255, 153, 204));
        blueprintsChoice.setOpaque(false);

        ImageIcon iconBp = new ImageIcon (getClass().getResource("/Images/blueprintsIcon.png"));
        Image imgBp = iconBp.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel3.setIcon(new javax.swing.ImageIcon(imgBp));
        buttonPanel3.setText("Szablony");
        buttonPanel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPanel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blueprintsChoiceLayout = new javax.swing.GroupLayout(blueprintsChoice);
        blueprintsChoice.setLayout(blueprintsChoiceLayout);
        blueprintsChoiceLayout.setHorizontalGroup(
            blueprintsChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blueprintsChoiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        blueprintsChoiceLayout.setVerticalGroup(
            blueprintsChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout archiveMenuCardLayout = new javax.swing.GroupLayout(archiveMenuCard);
        archiveMenuCard.setLayout(archiveMenuCardLayout);
        archiveMenuCardLayout.setHorizontalGroup(
            archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveMenuCardLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lastInvoicesChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(registryChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(blueprintsChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        archiveMenuCardLayout.setVerticalGroup(
            archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveMenuCardLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastInvoicesChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registryChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueprintsChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        background1.add(archiveMenuCard, "card4");

        remeberedPhrasesCard.setOpaque(false);

        suggestionsComboBox.setBackground(new java.awt.Color(30, 30, 30));
        suggestionsComboBox.setMaximumRowCount(8);
        suggestionsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Item 2", "Item 3", "Item 4" }));
        suggestionsComboBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suggestionsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suggestionsComboBoxActionPerformed(evt);
            }
        });

        suggestionsDisplayTextArea.setBackground(new java.awt.Color(30, 30, 30));
        suggestionsDisplayTextArea.setColumns(20);
        suggestionsDisplayTextArea.setRows(5);
        suggestionsDisplayTextArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(suggestionsDisplayTextArea);

        deleteSavedAutoFillCellButton.setBackground(new java.awt.Color(30, 30, 30));
        deleteSavedAutoFillCellButton.setText("Usuń");
        deleteSavedAutoFillCellButton.setBorderPainted(false);

        editSavedAutoFillCellButton.setBackground(new java.awt.Color(30, 30, 30));
        editSavedAutoFillCellButton.setText("Zapisz");
        editSavedAutoFillCellButton.setBorderPainted(false);

        javax.swing.GroupLayout roundedTile4Layout = new javax.swing.GroupLayout(roundedTile4);
        roundedTile4.setLayout(roundedTile4Layout);
        roundedTile4Layout.setHorizontalGroup(
            roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile4Layout.createSequentialGroup()
                .addGroup(roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedTile4Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(suggestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedTile4Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(deleteSavedAutoFillCellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editSavedAutoFillCellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        roundedTile4Layout.setVerticalGroup(
            roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundedTile4Layout.createSequentialGroup()
                        .addComponent(suggestionsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(roundedTile4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteSavedAutoFillCellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editSavedAutoFillCellButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout remeberedPhrasesCardLayout = new javax.swing.GroupLayout(remeberedPhrasesCard);
        remeberedPhrasesCard.setLayout(remeberedPhrasesCardLayout);
        remeberedPhrasesCardLayout.setHorizontalGroup(
            remeberedPhrasesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remeberedPhrasesCardLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(roundedTile4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        remeberedPhrasesCardLayout.setVerticalGroup(
            remeberedPhrasesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remeberedPhrasesCardLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(roundedTile4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        background1.add(remeberedPhrasesCard, "card4");

        savedInvoiceBlueprintCards.setOpaque(false);

        jScrollPane5.setBorder(null);
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setAutoscrolls(true);
        jScrollPane5.setOpaque(false);
        jScrollPane5.setViewportView(null);
        jScrollPane4.getViewport().setOpaque(false);
        jScrollPane4.getVerticalScrollBar().setUnitIncrement(20);

        savedInvoiceBlueprintDisplayPanel.setOpaque(false);
        savedInvoiceBlueprintDisplayPanel.setLayout(new java.awt.BorderLayout());
        savedInvoiceBlueprintDisplayPanel.add(invoiceButtonPanel2, java.awt.BorderLayout.CENTER);

        choseInvoiceDisplayPanel.setLayout(new WrapLayout(FlowLayout.LEFT, 30, 30));

        jScrollPane5.setViewportView(savedInvoiceBlueprintDisplayPanel);

        javax.swing.GroupLayout savedInvoiceBlueprintCardsLayout = new javax.swing.GroupLayout(savedInvoiceBlueprintCards);
        savedInvoiceBlueprintCards.setLayout(savedInvoiceBlueprintCardsLayout);
        savedInvoiceBlueprintCardsLayout.setHorizontalGroup(
            savedInvoiceBlueprintCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savedInvoiceBlueprintCardsLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        savedInvoiceBlueprintCardsLayout.setVerticalGroup(
            savedInvoiceBlueprintCardsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savedInvoiceBlueprintCardsLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        background1.add(savedInvoiceBlueprintCards, "card5");

        fillInvoiceDataCard.setOpaque(false);

        jScrollPane3.setBorder(null);
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setOpaque(false);
        jScrollPane3.setViewportView(null);
        jScrollPane3.getViewport().setOpaque(false);
        jScrollPane3.getVerticalScrollBar().setUnitIncrement(20);

        fillInvoiceDataRenderPanel.setOpaque(false);
        fillInvoiceDataRenderPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 89);
        fillInvoiceDataRenderPanel.add(invoiceDataTile1, gridBagConstraints);

        jScrollPane3.setViewportView(fillInvoiceDataRenderPanel);

        fillInvoiceGenerateButton.setBackground(new java.awt.Color(15, 15, 15));
        fillInvoiceGenerateButton.setText("Generuj");
        fillInvoiceGenerateButton.setBorderPainted(false);
        fillInvoiceGenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillInvoiceGenerateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fillInvoiceDataCardLayout = new javax.swing.GroupLayout(fillInvoiceDataCard);
        fillInvoiceDataCard.setLayout(fillInvoiceDataCardLayout);
        fillInvoiceDataCardLayout.setHorizontalGroup(
            fillInvoiceDataCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillInvoiceDataCardLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fillInvoiceDataCardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fillInvoiceGenerateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        fillInvoiceDataCardLayout.setVerticalGroup(
            fillInvoiceDataCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillInvoiceDataCardLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(fillInvoiceGenerateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        background1.add(fillInvoiceDataCard, "card5");

        choseInvoiceCard.setOpaque(false);

        jScrollPane4.setBorder(null);
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setOpaque(false);
        jScrollPane4.setViewportView(null);
        jScrollPane4.getViewport().setOpaque(false);
        jScrollPane4.getVerticalScrollBar().setUnitIncrement(20);

        choseInvoiceDisplayPanel.setOpaque(false);
        choseInvoiceDisplayPanel.setLayout(new java.awt.BorderLayout());
        choseInvoiceDisplayPanel.add(invoiceButtonPanel1, java.awt.BorderLayout.CENTER);

        choseInvoiceDisplayPanel.setLayout(new WrapLayout(FlowLayout.LEFT, 30, 30));

        jScrollPane4.setViewportView(choseInvoiceDisplayPanel);

        javax.swing.GroupLayout choseInvoiceCardLayout = new javax.swing.GroupLayout(choseInvoiceCard);
        choseInvoiceCard.setLayout(choseInvoiceCardLayout);
        choseInvoiceCardLayout.setHorizontalGroup(
            choseInvoiceCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choseInvoiceCardLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        choseInvoiceCardLayout.setVerticalGroup(
            choseInvoiceCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choseInvoiceCardLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        background1.add(choseInvoiceCard, "card5");

        selectInvoiceFileCard.setOpaque(false);

        selectInvoiceNameTextField.setBackground(new java.awt.Color(30, 30, 30));
        selectInvoiceNameTextField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        selectInvoiceNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        selectInvoiceNameTextField.setText("Nazwa Szablonu");
        selectInvoiceNameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        selectInvoiceNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                selectInvoiceNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                selectInvoiceNameTextFieldFocusLost(evt);
            }
        });
        selectInvoiceNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInvoiceNameTextFieldActionPerformed(evt);
            }
        });

        selectInvoiceFileButton.setBackground(new java.awt.Color(30, 30, 30));
        selectInvoiceFileButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectInvoiceFileButton.setText("Wybierz plik");
        selectInvoiceFileButton.setBorderPainted(false);
        selectInvoiceFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectInvoiceFileButtonActionPerformed(evt);
            }
        });

        proceedToTemplateConfigurationButton.setBackground(new java.awt.Color(30, 30, 30));
        proceedToTemplateConfigurationButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proceedToTemplateConfigurationButton.setText("Przejdź do konfiguracji");
        proceedToTemplateConfigurationButton.setBorderPainted(false);
        proceedToTemplateConfigurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedToTemplateConfigurationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedTile1Layout = new javax.swing.GroupLayout(roundedTile1);
        roundedTile1.setLayout(roundedTile1Layout);
        roundedTile1Layout.setHorizontalGroup(
            roundedTile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedTile1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(selectInvoiceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(roundedTile1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(selectInvoiceFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(roundedTile1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(proceedToTemplateConfigurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedTile1Layout.setVerticalGroup(
            roundedTile1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(selectInvoiceNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectInvoiceFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(proceedToTemplateConfigurationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout selectInvoiceFileCardLayout = new javax.swing.GroupLayout(selectInvoiceFileCard);
        selectInvoiceFileCard.setLayout(selectInvoiceFileCardLayout);
        selectInvoiceFileCardLayout.setHorizontalGroup(
            selectInvoiceFileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selectInvoiceFileCardLayout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(roundedTile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );
        selectInvoiceFileCardLayout.setVerticalGroup(
            selectInvoiceFileCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectInvoiceFileCardLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(roundedTile1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        background1.add(selectInvoiceFileCard, "card2");

        fillFormCard.setOpaque(false);

        parameterNameTf.setBackground(new java.awt.Color(30, 30, 30));
        parameterNameTf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        parameterNameTf.setText("Nazwa parametru");
        parameterNameTf.setBorder(new CompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), new EmptyBorder(0,10,0,0)));
        parameterNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                parameterNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                parameterNameTfFocusLost(evt);
            }
        });
        parameterNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameterNameTfActionPerformed(evt);
            }
        });

        cellNameTf.setBackground(new java.awt.Color(30, 30, 30));
        cellNameTf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cellNameTf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cellNameTf.setText("Komórka  (np. B3)");
        cellNameTf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cellNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cellNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cellNameTfFocusLost(evt);
            }
        });
        cellNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellNameTfActionPerformed(evt);
            }
        });

        addNewParameterButton.setBackground(new java.awt.Color(30, 30, 30));
        addNewParameterButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addNewParameterButton.setText("Dodaj");
        addNewParameterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addNewParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewParameterButtonActionPerformed(evt);
            }
        });

        paramCellCombo.setBackground(new java.awt.Color(30, 30, 30));
        paramCellCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paramCellCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramCellComboActionPerformed(evt);
            }
        });

        saveForm.setBackground(new java.awt.Color(30, 30, 30));
        saveForm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveForm.setText("Zapisz Szablon");
        saveForm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFormActionPerformed(evt);
            }
        });

        autoParamChoice.setBackground(new java.awt.Color(30, 30, 30));
        autoParamChoice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        autoParamChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Automatyzuj>", "Numer", "Data", "Cena - Całkowita", "Cena - Ile sztuk", "Cena - Jednostkowa", "Cena - Słownie" }));
        autoParamChoice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        autoParamChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoParamChoiceActionPerformed(evt);
            }
        });

        deleteParameterButton.setBackground(new java.awt.Color(30, 30, 30));
        deleteParameterButton.setText("Usuń");
        deleteParameterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteParameterButtonActionPerformed(evt);
            }
        });

        textAlignmentCombo.setBackground(new java.awt.Color(30, 30, 30));
        textAlignmentCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textAlignmentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Pozycja w komórce>", "Lewo", "Środek", "Prawo" }));
        textAlignmentCombo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textAlignmentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlignmentComboActionPerformed(evt);
            }
        });

        entrySubstringTf.setBackground(new java.awt.Color(30, 30, 30));
        entrySubstringTf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        entrySubstringTf.setText("Aby otoczyć wartość tekstem podaj go wraz z wartością zapisaną jako @ (np. teskt @ tekst)");
        entrySubstringTf.setBorder(new CompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), new EmptyBorder(0,10,0,0)));
        entrySubstringTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entrySubstringTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                entrySubstringTfFocusLost(evt);
            }
        });
        entrySubstringTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrySubstringTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedTile2Layout = new javax.swing.GroupLayout(roundedTile2);
        roundedTile2.setLayout(roundedTile2Layout);
        roundedTile2Layout.setHorizontalGroup(
            roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(roundedTile2Layout.createSequentialGroup()
                        .addComponent(paramCellCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(deleteParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedTile2Layout.createSequentialGroup()
                        .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addNewParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(entrySubstringTf, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(roundedTile2Layout.createSequentialGroup()
                                    .addComponent(parameterNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cellNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(autoParamChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(textAlignmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        roundedTile2Layout.setVerticalGroup(
            roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedTile2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parameterNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAlignmentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoParamChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(entrySubstringTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addNewParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(roundedTile2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paramCellCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteParameterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout fillFormCardLayout = new javax.swing.GroupLayout(fillFormCard);
        fillFormCard.setLayout(fillFormCardLayout);
        fillFormCardLayout.setHorizontalGroup(
            fillFormCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillFormCardLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(roundedTile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        fillFormCardLayout.setVerticalGroup(
            fillFormCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fillFormCardLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(roundedTile2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        background1.add(fillFormCard, "card2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1214, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(background1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(topMvPanelPlusButtons1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topMvPanelPlusButtons1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPanel2ActionPerformed

    private void buttonPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPanel3ActionPerformed

    private void buttonPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPanel1ActionPerformed

    private void buttonPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPanel1MousePressed
        //buttonPanel1.clickedColor();
    }//GEN-LAST:event_buttonPanel1MousePressed

    private void buttonPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPanel1MouseReleased
        //buttonPanel1.releasedColor();
    }//GEN-LAST:event_buttonPanel1MouseReleased

    private void selectInvoiceFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInvoiceFileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectInvoiceFileButtonActionPerformed

    private void selectInvoiceNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectInvoiceNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_selectInvoiceNameTextFieldFocusGained

    private void selectInvoiceNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_selectInvoiceNameTextFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_selectInvoiceNameTextFieldFocusLost

    private void selectInvoiceNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectInvoiceNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectInvoiceNameTextFieldActionPerformed

    private void parameterNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parameterNameTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterNameTfFocusGained

    private void parameterNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parameterNameTfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterNameTfFocusLost

    private void parameterNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameterNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterNameTfActionPerformed

    private void cellNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNameTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cellNameTfFocusGained

    private void cellNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNameTfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cellNameTfFocusLost

    private void addNewParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewParameterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewParameterButtonActionPerformed

    private void paramCellComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramCellComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paramCellComboActionPerformed

    private void saveFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveFormActionPerformed

    private void deleteParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteParameterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteParameterButtonActionPerformed

    private void autoParamChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoParamChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autoParamChoiceActionPerformed

    private void textAlignmentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlignmentComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlignmentComboActionPerformed

    private void entrySubstringTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySubstringTfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySubstringTfFocusGained

    private void entrySubstringTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entrySubstringTfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySubstringTfFocusLost

    private void entrySubstringTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrySubstringTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrySubstringTfActionPerformed

    private void proceedToTemplateConfigurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedToTemplateConfigurationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proceedToTemplateConfigurationButtonActionPerformed

    private void fillInvoiceGenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillInvoiceGenerateButtonActionPerformed
        invoiceGenerator.generateInvoice();
    }//GEN-LAST:event_fillInvoiceGenerateButtonActionPerformed

    private void cellNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellNameTfActionPerformed

    private void invoiceButtonPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceButtonPanel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceButtonPanel3ActionPerformed

    private void suggestionsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suggestionsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suggestionsComboBoxActionPerformed

    private void loadInvoices(){
        this.invoiceAdder = new InvoiceBlueprintAdder(invoiceCollection);
        reloadChoiceCombo();
    }
    
    private void reloadChoiceCombo(){

    }

    private void initCardLayout(){
        background1.remove(dashBoardPanelCard);
        background1.remove(archiveMenuCard);


        background1.add(dashBoardPanelCard, "0 0");
        background1.add(archiveMenuCard, "2 0");


    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    private InvoiceGenerator invoiceGenerator;
    private ConfigStorage configStorage;
    private Map<String,Invoice> invoiceCollection;
    private InvoiceBlueprintAdder invoiceAdder;
    private CardLayout cardLayout;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewParameterButton;
    private javax.swing.JPanel archiveMenuCard;
    private javax.swing.JComboBox<String> autoParamChoice;
    private com.woytuloo.accountingapp.component.Background background1;
    private javax.swing.JPanel blueprintsChoice;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel1;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel2;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel3;
    private javax.swing.JTextField cellNameTf;
    private javax.swing.JPanel choseInvoiceCard;
    private javax.swing.JPanel choseInvoiceDisplayPanel;
    private com.woytuloo.accountingapp.component.ControllJButton controllJButton1;
    private com.woytuloo.accountingapp.component.ControllJButtonMinimize controllJButtonMinimize1;
    private com.woytuloo.accountingapp.component.CustomScrollpane customScrollpane2;
    private javax.swing.JPanel dashBoardPanelCard;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel dashboardChartDisplayPanel;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel2 dashboardInfoDataPanel;
    private javax.swing.JButton deleteParameterButton;
    private javax.swing.JButton deleteSavedAutoFillCellButton;
    private javax.swing.JButton editSavedAutoFillCellButton;
    private javax.swing.JTextField entrySubstringTf;
    private javax.swing.JPanel fillFormCard;
    private javax.swing.JPanel fillInvoiceDataCard;
    private javax.swing.JPanel fillInvoiceDataRenderPanel;
    private javax.swing.JButton fillInvoiceGenerateButton;
    private javax.swing.JLabel incomeThisMonthLabel;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel3 incomeThisMonthPanel;
    private com.woytuloo.accountingapp.component.InvoiceButtonPanel invoiceButtonPanel1;
    private com.woytuloo.accountingapp.component.InvoiceButtonPanel invoiceButtonPanel2;
    private com.woytuloo.accountingapp.component.InvoiceButtonPanel invoiceButtonPanel3;
    private com.woytuloo.accountingapp.component.InvoiceDataTile invoiceDataTile1;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel3 invoicesThisMonthPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel lastInvoicesCard;
    private javax.swing.JPanel lastInvoicesChoice;
    private javax.swing.JPanel lastInvoicesRenderPanel;
    private javax.swing.JTextField lastInvoicesSearchBar;
    private javax.swing.JButton lastInvoicesSearchButton;
    private com.woytuloo.accountingapp.menu.Menu menu1;
    private com.woytuloo.accountingapp.component.mvPanel mvPanel1;
    private javax.swing.JComboBox<String> paramCellCombo;
    private javax.swing.JTextField parameterNameTf;
    private javax.swing.JButton proceedToTemplateConfigurationButton;
    private javax.swing.JPanel registryChoice;
    private javax.swing.JPanel remeberedPhrasesCard;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel3 roundedInfoPanel34;
    private com.woytuloo.accountingapp.component.RoundedTile roundedTile1;
    private com.woytuloo.accountingapp.component.RoundedTile roundedTile2;
    private com.woytuloo.accountingapp.component.RoundedTile roundedTile3;
    private com.woytuloo.accountingapp.component.RoundedTile roundedTile4;
    private javax.swing.JButton saveForm;
    private javax.swing.JPanel savedInvoiceBlueprintCards;
    private javax.swing.JPanel savedInvoiceBlueprintDisplayPanel;
    private javax.swing.JButton selectInvoiceFileButton;
    private javax.swing.JPanel selectInvoiceFileCard;
    private javax.swing.JTextField selectInvoiceNameTextField;
    private javax.swing.JComboBox<String> suggestionsComboBox;
    private javax.swing.JTextArea suggestionsDisplayTextArea;
    private javax.swing.JComboBox<String> textAlignmentCombo;
    private javax.swing.JLabel thisMonthInvoiceCountLabel;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel3 thisMonthlyTargetPanel;
    private javax.swing.JLabel thisMonthsTargetLabel;
    private com.woytuloo.accountingapp.component.TopMvPanelPlusButtons topMvPanelPlusButtons1;
    private javax.swing.JProgressBar yearlyIncomeProgressBar;
    // End of variables declaration//GEN-END:variables
}