/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.woytuloo.accountingapp.main;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.woytuloo.accountingapp.InvoiceManagement.Invoice;
import com.woytuloo.accountingapp.InvoiceManagement.InvoiceBlueprintAdder;
import com.woytuloo.accountingapp.charts.ChartsGenerator;
import com.woytuloo.accountingapp.menu.MenuEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Image;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author wojte
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        FlatDarculaLaf.setup();
        SwingUtilities.updateComponentTreeUI(this);
           
        
        initComponents();
        menu1.setEvent( new MenuEvent(){
            @Override
            public void selected(int index, int subIndex){
                    String indexStr = index + " " + subIndex;
                    cardLayout.show(background1,  indexStr);      
                System.out.println(index + " " + subIndex);
            }
        });
        mvPanel1.initMv(this);
        topMvPanelPlusButtons1.initMv(this);
        invoiceCollection = new HashMap<>();
        
        loadConfig();
        ChartsGenerator.showIncomeChart(roundedInfoPanel1.getIncomeChart());
        ChartsGenerator.showWorkDoneChart(roundedInfoPanel1.getWorkDoneChart());
        initCardLayout();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customScrollpane2 = new com.woytuloo.accountingapp.component.CustomScrollpane();
        menu1 = new com.woytuloo.accountingapp.menu.Menu();
        mvPanel1 = new com.woytuloo.accountingapp.component.mvPanel();
        topMvPanelPlusButtons1 = new com.woytuloo.accountingapp.component.TopMvPanelPlusButtons();
        controllJButton1 = new com.woytuloo.accountingapp.component.ControllJButton();
        jPanel2 = new javax.swing.JPanel();
        background1 = new com.woytuloo.accountingapp.component.Background();
        addNewForm = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        chooseNewBlueprint = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        blueprintNametf = new javax.swing.JTextField();
        parameterNameTf = new javax.swing.JTextField();
        cellNameTf = new javax.swing.JTextField();
        addNewParameterButton = new javax.swing.JButton();
        paramCellCombo = new javax.swing.JComboBox<>();
        saveForm = new javax.swing.JButton();
        deleteParameterButton = new javax.swing.JButton();
        newInvoice = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paramValueTable = new javax.swing.JTable();
        generateInvoice = new javax.swing.JButton();
        invoiceChoiceCombo = new javax.swing.JComboBox<>();
        dashBoardPanel = new javax.swing.JPanel();
        roundedInfoPanel1 = new com.woytuloo.accountingapp.component.RoundedInfoPanel();
        archiveMenuCard = new javax.swing.JPanel();
        lastInvoicesChoice = new javax.swing.JPanel();
        buttonPanel1 = new com.woytuloo.accountingapp.component.ButtonPanel();
        registryChoice = new javax.swing.JPanel();
        buttonPanel2 = new com.woytuloo.accountingapp.component.ButtonPanel();
        blueprintsChoice = new javax.swing.JPanel();
        buttonPanel3 = new com.woytuloo.accountingapp.component.ButtonPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 20));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(20, 20, 20));

        menu1.setBackground(new java.awt.Color(20, 20, 20));
        customScrollpane2.setViewportView(menu1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customScrollpane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mvPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mvPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customScrollpane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addContainerGap())
        );

        topMvPanelPlusButtons1.setBackground(new java.awt.Color(20, 20, 20));

        javax.swing.GroupLayout topMvPanelPlusButtons1Layout = new javax.swing.GroupLayout(topMvPanelPlusButtons1);
        topMvPanelPlusButtons1.setLayout(topMvPanelPlusButtons1Layout);
        topMvPanelPlusButtons1Layout.setHorizontalGroup(
            topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topMvPanelPlusButtons1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(controllJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topMvPanelPlusButtons1Layout.setVerticalGroup(
            topMvPanelPlusButtons1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controllJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.setBackground(new java.awt.Color(20, 20, 20));

        background1.setOpaque(true);
        cardLayout = new CardLayout();
        background1.setLayout(new java.awt.CardLayout());
        background1.setLayout(cardLayout);

        addNewForm.setOpaque(false);

        jPanel5.setBackground(new java.awt.Color(20, 20, 20));

        chooseNewBlueprint.setBackground(new java.awt.Color(51, 51, 51));
        chooseNewBlueprint.setText("Wybierz plik");
        chooseNewBlueprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseNewBlueprintActionPerformed(evt);
            }
        });

        fileNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        blueprintNametf.setBackground(new java.awt.Color(51, 51, 51));
        blueprintNametf.setText("Nazwa Szablonu");
        blueprintNametf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                blueprintNametfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                blueprintNametfFocusLost(evt);
            }
        });
        blueprintNametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueprintNametfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blueprintNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(fileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chooseNewBlueprint, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blueprintNametf)
                    .addComponent(chooseNewBlueprint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(fileNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        parameterNameTf.setBackground(new java.awt.Color(51, 51, 51));
        parameterNameTf.setText("Nazwa parametru");
        parameterNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                parameterNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                parameterNameTfFocusLost(evt);
            }
        });
        parameterNameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameterNameTfActionPerformed(evt);
            }
        });

        cellNameTf.setBackground(new java.awt.Color(51, 51, 51));
        cellNameTf.setText("Komórka  (np. B3)");
        cellNameTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cellNameTfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cellNameTfFocusLost(evt);
            }
        });

        addNewParameterButton.setBackground(new java.awt.Color(51, 51, 51));
        addNewParameterButton.setText("Dodaj");
        addNewParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewParameterButtonActionPerformed(evt);
            }
        });

        paramCellCombo.setBackground(new java.awt.Color(51, 51, 51));
        paramCellCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paramCellComboActionPerformed(evt);
            }
        });

        saveForm.setBackground(new java.awt.Color(51, 51, 51));
        saveForm.setText("Zapisz Szablon");
        saveForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFormActionPerformed(evt);
            }
        });

        deleteParameterButton.setBackground(new java.awt.Color(51, 51, 51));
        deleteParameterButton.setText("Usuń");
        deleteParameterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteParameterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewFormLayout = new javax.swing.GroupLayout(addNewForm);
        addNewForm.setLayout(addNewFormLayout);
        addNewFormLayout.setHorizontalGroup(
            addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewFormLayout.createSequentialGroup()
                .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewFormLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addNewFormLayout.createSequentialGroup()
                            .addGap(268, 268, 268)
                            .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(paramCellCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(parameterNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(addNewFormLayout.createSequentialGroup()
                            .addGap(572, 572, 572)
                            .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(deleteParameterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cellNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewFormLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addNewParameterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewFormLayout.createSequentialGroup()
                                    .addComponent(saveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(189, 189, 189))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        addNewFormLayout.setVerticalGroup(
            addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewFormLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parameterNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellNameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNewParameterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addGroup(addNewFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paramCellCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(deleteParameterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(84, 84, 84)
                .addComponent(saveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );

        background1.add(addNewForm, "card4");

        newInvoice.setOpaque(false);

        paramValueTable.setBackground(new java.awt.Color(51, 51, 51));
        paramValueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Parametr", "Wartość"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(paramValueTable);

        generateInvoice.setBackground(new java.awt.Color(51, 51, 51));
        generateInvoice.setText("Generuj");

        invoiceChoiceCombo.setBackground(new java.awt.Color(51, 51, 51));
        invoiceChoiceCombo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                invoiceChoiceComboFocusGained(evt);
            }
        });

        javax.swing.GroupLayout newInvoiceLayout = new javax.swing.GroupLayout(newInvoice);
        newInvoice.setLayout(newInvoiceLayout);
        newInvoiceLayout.setHorizontalGroup(
            newInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInvoiceLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(newInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceChoiceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        newInvoiceLayout.setVerticalGroup(
            newInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInvoiceLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(invoiceChoiceCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(generateInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        background1.add(newInvoice, "card5");

        dashBoardPanel.setForeground(new java.awt.Color(255, 255, 255));
        dashBoardPanel.setOpaque(false);

        roundedInfoPanel1.setBackground(new java.awt.Color(255, 0, 102));

        javax.swing.GroupLayout dashBoardPanelLayout = new javax.swing.GroupLayout(dashBoardPanel);
        dashBoardPanel.setLayout(dashBoardPanelLayout);
        dashBoardPanelLayout.setHorizontalGroup(
            dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedInfoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE)
                .addContainerGap())
        );
        dashBoardPanelLayout.setVerticalGroup(
            dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(397, Short.MAX_VALUE))
        );

        background1.add(dashBoardPanel, "card2");

        archiveMenuCard.setOpaque(false);

        lastInvoicesChoice.setBackground(new java.awt.Color(0, 153, 204));
        lastInvoicesChoice.setOpaque(false);

        buttonPanel1.setBorder(null);
        ImageIcon iconInvoice = new ImageIcon (getClass().getResource("/Images/lastinvoicesIcon.png"));
        Image imgInvoice = iconInvoice.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel1.setIcon(new ImageIcon(imgInvoice));
        buttonPanel1.setText("Ostatnie Faktury");
        buttonPanel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonPanel1MouseReleased(evt);
            }
        });
        buttonPanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lastInvoicesChoiceLayout = new javax.swing.GroupLayout(lastInvoicesChoice);
        lastInvoicesChoice.setLayout(lastInvoicesChoiceLayout);
        lastInvoicesChoiceLayout.setHorizontalGroup(
            lastInvoicesChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        lastInvoicesChoiceLayout.setVerticalGroup(
            lastInvoicesChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        registryChoice.setBackground(new java.awt.Color(153, 153, 255));
        registryChoice.setOpaque(false);

        ImageIcon iconReg = new ImageIcon (getClass().getResource("/Images/registryIcon.png"));
        Image imgReg = iconReg.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel2.setIcon(new javax.swing.ImageIcon(imgReg));
        buttonPanel2.setText("Spis podpowiedzi");
        buttonPanel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registryChoiceLayout = new javax.swing.GroupLayout(registryChoice);
        registryChoice.setLayout(registryChoiceLayout);
        registryChoiceLayout.setHorizontalGroup(
            registryChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        registryChoiceLayout.setVerticalGroup(
            registryChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        blueprintsChoice.setBackground(new java.awt.Color(255, 153, 204));
        blueprintsChoice.setOpaque(false);

        ImageIcon iconBp = new ImageIcon (getClass().getResource("/Images/blueprintsIcon.png"));
        Image imgBp = iconBp.getImage().getScaledInstance(200, 200,  java.awt.Image.SCALE_SMOOTH);
        buttonPanel3.setIcon(new javax.swing.ImageIcon(imgBp));
        buttonPanel3.setText("Szablony");
        buttonPanel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPanel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPanel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blueprintsChoiceLayout = new javax.swing.GroupLayout(blueprintsChoice);
        blueprintsChoice.setLayout(blueprintsChoiceLayout);
        blueprintsChoiceLayout.setHorizontalGroup(
            blueprintsChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blueprintsChoiceLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        blueprintsChoiceLayout.setVerticalGroup(
            blueprintsChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout archiveMenuCardLayout = new javax.swing.GroupLayout(archiveMenuCard);
        archiveMenuCard.setLayout(archiveMenuCardLayout);
        archiveMenuCardLayout.setHorizontalGroup(
            archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveMenuCardLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lastInvoicesChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(registryChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(blueprintsChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        archiveMenuCardLayout.setVerticalGroup(
            archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveMenuCardLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(archiveMenuCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastInvoicesChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registryChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueprintsChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        background1.add(archiveMenuCard, "card4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(topMvPanelPlusButtons1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topMvPanelPlusButtons1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPanel2ActionPerformed

    private void chooseNewBlueprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseNewBlueprintActionPerformed
        this.invoiceAdder = new InvoiceBlueprintAdder(fileNameLabel, invoiceCollection);
        invoiceAdder.addNewBlueprint();
        
    }//GEN-LAST:event_chooseNewBlueprintActionPerformed

    private void parameterNameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameterNameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parameterNameTfActionPerformed

    private void addNewParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewParameterButtonActionPerformed
        if(!cellNameTf.getText().isEmpty() && !parameterNameTf.getText().isEmpty()){
            String paramCell = parameterNameTf.getText() + ":" + cellNameTf.getText();
            boolean found = false;
            for(int i=0; i < paramCellCombo.getItemCount(); i++){
                if(paramCellCombo.getItemAt(i).equals(paramCell))
                    found = true;
            }
            if(!found)
                paramCellCombo.addItem(paramCell);
        }
    }//GEN-LAST:event_addNewParameterButtonActionPerformed

    private void saveFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFormActionPerformed
        if(!blueprintNametf.getText().equals("Nazwa Szablonu"))
            new JOptionPane().setVisible(true);
        
        Map<String, String> map= new HashMap<>();
        for(int i=0;i<paramCellCombo.getItemCount(); i++){
            String[] params = paramCellCombo.getItemAt(i).split(":");
            map.put(params[0], params[1]);
        }
        invoiceAdder.fillCollection(blueprintNametf.getText(), map);

    }//GEN-LAST:event_saveFormActionPerformed

    private void paramCellComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paramCellComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paramCellComboActionPerformed

    private void blueprintNametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueprintNametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueprintNametfActionPerformed

    private void deleteParameterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteParameterButtonActionPerformed
        Object obj = paramCellCombo.getSelectedItem();
        if(obj != null)
            paramCellCombo.removeItem(obj); 
    }//GEN-LAST:event_deleteParameterButtonActionPerformed

    private void parameterNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parameterNameTfFocusGained
        if(this.parameterNameTf.getText().equals("Nazwa parametru"))
            this.parameterNameTf.setText("");
    }//GEN-LAST:event_parameterNameTfFocusGained

    private void parameterNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_parameterNameTfFocusLost
        if(parameterNameTf.getText().equals(""))
            this.parameterNameTf.setText("Nazwa parametru");
    }//GEN-LAST:event_parameterNameTfFocusLost

    private void cellNameTfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNameTfFocusLost
        if(cellNameTf.getText().equals(""))
            this.cellNameTf.setText("Komórka  (np. B3)");
    }//GEN-LAST:event_cellNameTfFocusLost

    private void cellNameTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNameTfFocusGained
        if(this.cellNameTf.getText().equals("Komórka  (np. B3)"))
            this.cellNameTf.setText("");
    }//GEN-LAST:event_cellNameTfFocusGained

    private void buttonPanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPanel3ActionPerformed

    private void blueprintNametfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_blueprintNametfFocusGained
        if(this.blueprintNametf.getText().equals("Nazwa Szablonu"))
            this.blueprintNametf.setText("");
    }//GEN-LAST:event_blueprintNametfFocusGained

    private void blueprintNametfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_blueprintNametfFocusLost
        if(blueprintNametf.getText().equals(""))
            this.blueprintNametf.setText("Nazwa Szablonu");
    }//GEN-LAST:event_blueprintNametfFocusLost

    private void invoiceChoiceComboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_invoiceChoiceComboFocusGained
        this.invoiceCollection.forEach((name,invoice)->{
            for(int i = 0 ; i < invoiceChoiceCombo.getItemCount() ; i++){
                if(invoiceChoiceCombo.getItemAt(i).equals(name))
                    return;
            }
            this.invoiceChoiceCombo.addItem(name);
        });
    }//GEN-LAST:event_invoiceChoiceComboFocusGained

    private void buttonPanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPanel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPanel1ActionPerformed

    private void buttonPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPanel1MousePressed
        //buttonPanel1.clickedColor();
    }//GEN-LAST:event_buttonPanel1MousePressed

    private void buttonPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPanel1MouseReleased
        //buttonPanel1.releasedColor();
    }//GEN-LAST:event_buttonPanel1MouseReleased

    private void loadConfig(){
        this.invoiceAdder = new InvoiceBlueprintAdder(invoiceCollection);
    }

    private void initCardLayout(){
        background1.remove(dashBoardPanel);
        background1.remove(archiveMenuCard);
        background1.remove(addNewForm);
        background1.remove(newInvoice);

        background1.add(dashBoardPanel, "0 0");
        background1.add(archiveMenuCard, "2 0");
        background1.add(addNewForm, "1 2");
        background1.add(newInvoice, "1 1");
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    private Map<String,Invoice> invoiceCollection;
    private InvoiceBlueprintAdder invoiceAdder;
    private CardLayout cardLayout;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addNewForm;
    private javax.swing.JButton addNewParameterButton;
    private javax.swing.JPanel archiveMenuCard;
    private com.woytuloo.accountingapp.component.Background background1;
    private javax.swing.JTextField blueprintNametf;
    private javax.swing.JPanel blueprintsChoice;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel1;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel2;
    private com.woytuloo.accountingapp.component.ButtonPanel buttonPanel3;
    private javax.swing.JTextField cellNameTf;
    private javax.swing.JButton chooseNewBlueprint;
    private com.woytuloo.accountingapp.component.ControllJButton controllJButton1;
    private com.woytuloo.accountingapp.component.CustomScrollpane customScrollpane2;
    private javax.swing.JPanel dashBoardPanel;
    private javax.swing.JButton deleteParameterButton;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JButton generateInvoice;
    private javax.swing.JComboBox<String> invoiceChoiceCombo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lastInvoicesChoice;
    private com.woytuloo.accountingapp.menu.Menu menu1;
    private com.woytuloo.accountingapp.component.mvPanel mvPanel1;
    private javax.swing.JPanel newInvoice;
    private javax.swing.JComboBox<String> paramCellCombo;
    private javax.swing.JTable paramValueTable;
    private javax.swing.JTextField parameterNameTf;
    private javax.swing.JPanel registryChoice;
    private com.woytuloo.accountingapp.component.RoundedInfoPanel roundedInfoPanel1;
    private javax.swing.JButton saveForm;
    private com.woytuloo.accountingapp.component.TopMvPanelPlusButtons topMvPanelPlusButtons1;
    // End of variables declaration//GEN-END:variables
}
